// <auto-generated />
using System;
using Kartverket_group2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kartverket_group2.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241102183849_SeedSubmissionData")]
    partial class SeedSubmissionData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Kartverket_group2.Models.Submission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "comment");

                    b.Property<string>("GeoJsonData")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "geoJsonData");

                    b.Property<string>("Municipalitynr")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "municipalitynr");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "status");

                    b.Property<string>("Timestamp")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "timestamp");

                    b.HasKey("Id");

                    b.ToTable("Submissions");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Comment = "Test submission 1",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[10.1,60.1]},\"properties\":{\"id\":1,\"type\":\"Road\",\"comment\":\"Feature comment 1\",\"addedAt\":\"2024-11-01T18:38:48.8813325Z\",\"lastEdited\":\"2024-11-02T17:38:48.8813327Z\",\"radius\":10.5}}],\"activeTileLayer\":\"Topographic\"}",
                            Municipalitynr = "3001",
                            Status = "Uåpnet",
                            Timestamp = "2024-11-01T18:38:48.8813287Z"
                        },
                        new
                        {
                            Id = 2L,
                            Comment = "Test submission 2",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[10.2,60.2]},\"properties\":{\"id\":2,\"type\":\"Building\",\"comment\":\"Feature comment 2\",\"addedAt\":\"2024-10-31T18:38:48.8813339Z\",\"lastEdited\":\"2024-11-02T16:38:48.8813339Z\",\"radius\":21}}],\"activeTileLayer\":\"Topographic\"}",
                            Municipalitynr = "3002",
                            Status = "Under behandling",
                            Timestamp = "2024-10-31T18:38:48.8813335Z"
                        },
                        new
                        {
                            Id = 3L,
                            Comment = "Test submission 3",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[10.3,60.3]},\"properties\":{\"id\":3,\"type\":\"Road\",\"comment\":\"Feature comment 3\",\"addedAt\":\"2024-10-30T18:38:48.8813345Z\",\"lastEdited\":\"2024-11-02T15:38:48.8813345Z\",\"radius\":31.5}}],\"activeTileLayer\":\"Topographic\"}",
                            Municipalitynr = "3003",
                            Status = "Behandlet",
                            Timestamp = "2024-10-30T18:38:48.8813341Z"
                        },
                        new
                        {
                            Id = 4L,
                            Comment = "Test submission 4",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[10.4,60.4]},\"properties\":{\"id\":4,\"type\":\"Building\",\"comment\":\"Feature comment 4\",\"addedAt\":\"2024-10-29T18:38:48.8813350Z\",\"lastEdited\":\"2024-11-02T14:38:48.8813351Z\",\"radius\":42}}],\"activeTileLayer\":\"Topographic\"}",
                            Municipalitynr = "3004",
                            Status = "Under behandling",
                            Timestamp = "2024-10-29T18:38:48.8813348Z"
                        },
                        new
                        {
                            Id = 5L,
                            Comment = "Test submission 5",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[10.5,60.5]},\"properties\":{\"id\":5,\"type\":\"Road\",\"comment\":\"Feature comment 5\",\"addedAt\":\"2024-10-28T18:38:48.8813356Z\",\"lastEdited\":\"2024-11-02T13:38:48.8813357Z\",\"radius\":52.5}}],\"activeTileLayer\":\"Topographic\"}",
                            Municipalitynr = "3005",
                            Status = "Uåpnet",
                            Timestamp = "2024-10-28T18:38:48.8813353Z"
                        },
                        new
                        {
                            Id = 6L,
                            Comment = "Test submission 6",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[10.6,60.6]},\"properties\":{\"id\":6,\"type\":\"Building\",\"comment\":\"Feature comment 6\",\"addedAt\":\"2024-10-27T18:38:48.8813363Z\",\"lastEdited\":\"2024-11-02T12:38:48.8813364Z\",\"radius\":63}}],\"activeTileLayer\":\"Topographic\"}",
                            Municipalitynr = "3006",
                            Status = "Behandlet",
                            Timestamp = "2024-10-27T18:38:48.8813361Z"
                        },
                        new
                        {
                            Id = 7L,
                            Comment = "Test submission 7",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[10.7,60.7]},\"properties\":{\"id\":7,\"type\":\"Road\",\"comment\":\"Feature comment 7\",\"addedAt\":\"2024-10-26T18:38:48.8813369Z\",\"lastEdited\":\"2024-11-02T11:38:48.8813370Z\",\"radius\":73.5}}],\"activeTileLayer\":\"Topographic\"}",
                            Municipalitynr = "3007",
                            Status = "Uåpnet",
                            Timestamp = "2024-10-26T18:38:48.8813366Z"
                        },
                        new
                        {
                            Id = 8L,
                            Comment = "Test submission 8",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[10.8,60.8]},\"properties\":{\"id\":8,\"type\":\"Building\",\"comment\":\"Feature comment 8\",\"addedAt\":\"2024-10-25T18:38:48.8813375Z\",\"lastEdited\":\"2024-11-02T10:38:48.8813375Z\",\"radius\":84}}],\"activeTileLayer\":\"Topographic\"}",
                            Municipalitynr = "3008",
                            Status = "Under behandling",
                            Timestamp = "2024-10-25T18:38:48.8813372Z"
                        },
                        new
                        {
                            Id = 9L,
                            Comment = "Test submission 9",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[10.9,60.9]},\"properties\":{\"id\":9,\"type\":\"Road\",\"comment\":\"Feature comment 9\",\"addedAt\":\"2024-10-24T18:38:48.8813411Z\",\"lastEdited\":\"2024-11-02T09:38:48.8813412Z\",\"radius\":94.5}}],\"activeTileLayer\":\"Topographic\"}",
                            Municipalitynr = "3009",
                            Status = "Behandlet",
                            Timestamp = "2024-10-24T18:38:48.8813377Z"
                        },
                        new
                        {
                            Id = 10L,
                            Comment = "Test submission 10",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[11,61]},\"properties\":{\"id\":10,\"type\":\"Building\",\"comment\":\"Feature comment 10\",\"addedAt\":\"2024-10-23T18:38:48.8813419Z\",\"lastEdited\":\"2024-11-02T08:38:48.8813419Z\",\"radius\":105}}],\"activeTileLayer\":\"Topographic\"}",
                            Municipalitynr = "3010",
                            Status = "Under behandling",
                            Timestamp = "2024-10-23T18:38:48.8813416Z"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
