// <auto-generated />
using System;
using Kartverket_group2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kartverket_group2.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241102190527_SeedSubmissionData3")]
    partial class SeedSubmissionData3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Kartverket_group2.Models.Submission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "comment");

                    b.Property<string>("GeoJsonData")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "geoJsonData");

                    b.Property<string>("Municipalitynr")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "municipalitynr");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "status");

                    b.Property<string>("Timestamp")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "timestamp");

                    b.HasKey("Id");

                    b.ToTable("Submissions");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Comment = "Test submission 1",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[8.11234512345,58.117571427]},\"properties\":{\"id\":1,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 1\",\"addedAt\":\"2024-11-01T19:05:27.3583690Z\",\"lastEdited\":\"2024-11-02T18:05:27.3583691Z\",\"radius\":10.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3001",
                            Status = "Uåpnet",
                            Timestamp = "2024-11-01T19:05:27.3583657Z"
                        },
                        new
                        {
                            Id = 2L,
                            Comment = "Test submission 2",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[8.2246902469,58.235142854]},\"properties\":{\"id\":2,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 2\",\"addedAt\":\"2024-10-31T19:05:27.3583701Z\",\"lastEdited\":\"2024-11-02T17:05:27.3583702Z\",\"radius\":21}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3002",
                            Status = "Under arbeid",
                            Timestamp = "2024-10-31T19:05:27.3583698Z"
                        },
                        new
                        {
                            Id = 3L,
                            Comment = "Test submission 3",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[8.33703537035,58.352714281]},\"properties\":{\"id\":3,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 3\",\"addedAt\":\"2024-10-30T19:05:27.3583706Z\",\"lastEdited\":\"2024-11-02T16:05:27.3583707Z\",\"radius\":31.5}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3003",
                            Status = "Akseptert",
                            Timestamp = "2024-10-30T19:05:27.3583704Z"
                        },
                        new
                        {
                            Id = 4L,
                            Comment = "Test submission 4",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[8.4493804938,58.470285708]},\"properties\":{\"id\":4,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 4\",\"addedAt\":\"2024-10-29T19:05:27.3583712Z\",\"lastEdited\":\"2024-11-02T15:05:27.3583712Z\",\"radius\":42}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3004",
                            Status = "Under arbeid",
                            Timestamp = "2024-10-29T19:05:27.3583709Z"
                        },
                        new
                        {
                            Id = 5L,
                            Comment = "Test submission 5",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[8.56172561725,58.587857135]},\"properties\":{\"id\":5,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 5\",\"addedAt\":\"2024-10-28T19:05:27.3583716Z\",\"lastEdited\":\"2024-11-02T14:05:27.3583717Z\",\"radius\":52.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3005",
                            Status = "Uåpnet",
                            Timestamp = "2024-10-28T19:05:27.3583714Z"
                        },
                        new
                        {
                            Id = 6L,
                            Comment = "Test submission 6",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[8.6740707407,58.705428562]},\"properties\":{\"id\":6,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 6\",\"addedAt\":\"2024-10-27T19:05:27.3583762Z\",\"lastEdited\":\"2024-11-02T13:05:27.3583763Z\",\"radius\":63}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3006",
                            Status = "Akseptert",
                            Timestamp = "2024-10-27T19:05:27.3583758Z"
                        },
                        new
                        {
                            Id = 7L,
                            Comment = "Test submission 7",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[8.78641586415,58.822999989]},\"properties\":{\"id\":7,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 7\",\"addedAt\":\"2024-10-26T19:05:27.3583768Z\",\"lastEdited\":\"2024-11-02T12:05:27.3583769Z\",\"radius\":73.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3007",
                            Status = "Uåpnet",
                            Timestamp = "2024-10-26T19:05:27.3583765Z"
                        },
                        new
                        {
                            Id = 8L,
                            Comment = "Test submission 8",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[8.8987609876,58.940571416]},\"properties\":{\"id\":8,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 8\",\"addedAt\":\"2024-10-25T19:05:27.3583773Z\",\"lastEdited\":\"2024-11-02T11:05:27.3583774Z\",\"radius\":84}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3008",
                            Status = "Under arbeid",
                            Timestamp = "2024-10-25T19:05:27.3583770Z"
                        },
                        new
                        {
                            Id = 9L,
                            Comment = "Test submission 9",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[9.01110611105,59.058142843]},\"properties\":{\"id\":9,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 9\",\"addedAt\":\"2024-10-24T19:05:27.3583778Z\",\"lastEdited\":\"2024-11-02T10:05:27.3583779Z\",\"radius\":94.5}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3009",
                            Status = "Akseptert",
                            Timestamp = "2024-10-24T19:05:27.3583775Z"
                        },
                        new
                        {
                            Id = 10L,
                            Comment = "Test submission 10",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[9.1234512345,59.17571427]},\"properties\":{\"id\":10,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 10\",\"addedAt\":\"2024-10-23T19:05:27.3583784Z\",\"lastEdited\":\"2024-11-02T09:05:27.3583785Z\",\"radius\":105}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3010",
                            Status = "Under arbeid",
                            Timestamp = "2024-10-23T19:05:27.3583782Z"
                        },
                        new
                        {
                            Id = 11L,
                            Comment = "Test submission 11",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[9.23579635795,59.293285697]},\"properties\":{\"id\":11,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 11\",\"addedAt\":\"2024-10-22T19:05:27.3583790Z\",\"lastEdited\":\"2024-11-02T08:05:27.3583790Z\",\"radius\":115.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3011",
                            Status = "Uåpnet",
                            Timestamp = "2024-10-22T19:05:27.3583787Z"
                        },
                        new
                        {
                            Id = 12L,
                            Comment = "Test submission 12",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[9.348141481399999,59.410857124]},\"properties\":{\"id\":12,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 12\",\"addedAt\":\"2024-10-21T19:05:27.3583795Z\",\"lastEdited\":\"2024-11-02T07:05:27.3583796Z\",\"radius\":126}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3012",
                            Status = "Akseptert",
                            Timestamp = "2024-10-21T19:05:27.3583792Z"
                        },
                        new
                        {
                            Id = 13L,
                            Comment = "Test submission 13",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[9.46048660485,59.528428551]},\"properties\":{\"id\":13,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 13\",\"addedAt\":\"2024-10-20T19:05:27.3583800Z\",\"lastEdited\":\"2024-11-02T06:05:27.3583801Z\",\"radius\":136.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3013",
                            Status = "Uåpnet",
                            Timestamp = "2024-10-20T19:05:27.3583797Z"
                        },
                        new
                        {
                            Id = 14L,
                            Comment = "Test submission 14",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[9.5728317283,59.645999978]},\"properties\":{\"id\":14,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 14\",\"addedAt\":\"2024-10-19T19:05:27.3583805Z\",\"lastEdited\":\"2024-11-02T05:05:27.3583806Z\",\"radius\":147}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3014",
                            Status = "Under arbeid",
                            Timestamp = "2024-10-19T19:05:27.3583802Z"
                        },
                        new
                        {
                            Id = 15L,
                            Comment = "Test submission 15",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[9.68517685175,59.763571405]},\"properties\":{\"id\":15,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 15\",\"addedAt\":\"2024-10-18T19:05:27.3583810Z\",\"lastEdited\":\"2024-11-02T04:05:27.3583811Z\",\"radius\":157.5}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3015",
                            Status = "Akseptert",
                            Timestamp = "2024-10-18T19:05:27.3583808Z"
                        },
                        new
                        {
                            Id = 16L,
                            Comment = "Test submission 16",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[9.7975219752,59.881142832]},\"properties\":{\"id\":16,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 16\",\"addedAt\":\"2024-10-17T19:05:27.3583831Z\",\"lastEdited\":\"2024-11-02T03:05:27.3583831Z\",\"radius\":168}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3016",
                            Status = "Under arbeid",
                            Timestamp = "2024-10-17T19:05:27.3583828Z"
                        },
                        new
                        {
                            Id = 17L,
                            Comment = "Test submission 17",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[9.90986709865,59.998714259]},\"properties\":{\"id\":17,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 17\",\"addedAt\":\"2024-10-16T19:05:27.3583836Z\",\"lastEdited\":\"2024-11-02T02:05:27.3583837Z\",\"radius\":178.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3017",
                            Status = "Uåpnet",
                            Timestamp = "2024-10-16T19:05:27.3583833Z"
                        },
                        new
                        {
                            Id = 18L,
                            Comment = "Test submission 18",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[10.0222122221,60.116285686]},\"properties\":{\"id\":18,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 18\",\"addedAt\":\"2024-10-15T19:05:27.3583842Z\",\"lastEdited\":\"2024-11-02T01:05:27.3583843Z\",\"radius\":189}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3018",
                            Status = "Akseptert",
                            Timestamp = "2024-10-15T19:05:27.3583839Z"
                        },
                        new
                        {
                            Id = 19L,
                            Comment = "Test submission 19",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[10.13455734555,60.233857113]},\"properties\":{\"id\":19,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 19\",\"addedAt\":\"2024-10-14T19:05:27.3583847Z\",\"lastEdited\":\"2024-11-02T00:05:27.3583848Z\",\"radius\":199.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3019",
                            Status = "Uåpnet",
                            Timestamp = "2024-10-14T19:05:27.3583844Z"
                        },
                        new
                        {
                            Id = 20L,
                            Comment = "Test submission 20",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[10.246902469,60.35142854]},\"properties\":{\"id\":20,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 20\",\"addedAt\":\"2024-10-13T19:05:27.3583852Z\",\"lastEdited\":\"2024-11-01T23:05:27.3583853Z\",\"radius\":210}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3020",
                            Status = "Under arbeid",
                            Timestamp = "2024-10-13T19:05:27.3583849Z"
                        },
                        new
                        {
                            Id = 21L,
                            Comment = "Test submission 21",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[10.35924759245,60.468999967]},\"properties\":{\"id\":21,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 21\",\"addedAt\":\"2024-10-12T19:05:27.3583857Z\",\"lastEdited\":\"2024-11-01T22:05:27.3583858Z\",\"radius\":220.5}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3021",
                            Status = "Akseptert",
                            Timestamp = "2024-10-12T19:05:27.3583855Z"
                        },
                        new
                        {
                            Id = 22L,
                            Comment = "Test submission 22",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[10.4715927159,60.586571394]},\"properties\":{\"id\":22,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 22\",\"addedAt\":\"2024-10-11T19:05:27.3583862Z\",\"lastEdited\":\"2024-11-01T21:05:27.3583863Z\",\"radius\":231}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3022",
                            Status = "Under arbeid",
                            Timestamp = "2024-10-11T19:05:27.3583860Z"
                        },
                        new
                        {
                            Id = 23L,
                            Comment = "Test submission 23",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[10.58393783935,60.704142821]},\"properties\":{\"id\":23,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 23\",\"addedAt\":\"2024-10-10T19:05:27.3583867Z\",\"lastEdited\":\"2024-11-01T20:05:27.3583868Z\",\"radius\":241.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3023",
                            Status = "Uåpnet",
                            Timestamp = "2024-10-10T19:05:27.3583865Z"
                        },
                        new
                        {
                            Id = 24L,
                            Comment = "Test submission 24",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[10.6962829628,60.821714248]},\"properties\":{\"id\":24,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 24\",\"addedAt\":\"2024-10-09T19:05:27.3583873Z\",\"lastEdited\":\"2024-11-01T19:05:27.3583873Z\",\"radius\":252}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3024",
                            Status = "Akseptert",
                            Timestamp = "2024-10-09T19:05:27.3583870Z"
                        },
                        new
                        {
                            Id = 25L,
                            Comment = "Test submission 25",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[10.80862808625,60.939285675]},\"properties\":{\"id\":25,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 25\",\"addedAt\":\"2024-10-08T19:05:27.3583926Z\",\"lastEdited\":\"2024-11-01T18:05:27.3583926Z\",\"radius\":262.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3025",
                            Status = "Uåpnet",
                            Timestamp = "2024-10-08T19:05:27.3583875Z"
                        },
                        new
                        {
                            Id = 26L,
                            Comment = "Test submission 26",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[10.9209732097,61.056857102]},\"properties\":{\"id\":26,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 26\",\"addedAt\":\"2024-10-07T19:05:27.3583931Z\",\"lastEdited\":\"2024-11-01T17:05:27.3583932Z\",\"radius\":273}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3026",
                            Status = "Under arbeid",
                            Timestamp = "2024-10-07T19:05:27.3583928Z"
                        },
                        new
                        {
                            Id = 27L,
                            Comment = "Test submission 27",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[11.03331833315,61.174428529]},\"properties\":{\"id\":27,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 27\",\"addedAt\":\"2024-10-06T19:05:27.3583936Z\",\"lastEdited\":\"2024-11-01T16:05:27.3583937Z\",\"radius\":283.5}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3027",
                            Status = "Akseptert",
                            Timestamp = "2024-10-06T19:05:27.3583934Z"
                        },
                        new
                        {
                            Id = 28L,
                            Comment = "Test submission 28",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[11.1456634566,61.291999956]},\"properties\":{\"id\":28,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 28\",\"addedAt\":\"2024-10-05T19:05:27.3583941Z\",\"lastEdited\":\"2024-11-01T15:05:27.3583942Z\",\"radius\":294}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3028",
                            Status = "Under arbeid",
                            Timestamp = "2024-10-05T19:05:27.3583939Z"
                        },
                        new
                        {
                            Id = 29L,
                            Comment = "Test submission 29",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[11.25800858005,61.409571383]},\"properties\":{\"id\":29,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 29\",\"addedAt\":\"2024-10-04T19:05:27.3583946Z\",\"lastEdited\":\"2024-11-01T14:05:27.3583947Z\",\"radius\":304.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3029",
                            Status = "Uåpnet",
                            Timestamp = "2024-10-04T19:05:27.3583944Z"
                        },
                        new
                        {
                            Id = 30L,
                            Comment = "Test submission 30",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[11.370353703500001,61.52714281]},\"properties\":{\"id\":30,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 30\",\"addedAt\":\"2024-10-03T19:05:27.3583951Z\",\"lastEdited\":\"2024-11-01T13:05:27.3583952Z\",\"radius\":315}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3030",
                            Status = "Akseptert",
                            Timestamp = "2024-10-03T19:05:27.3583949Z"
                        },
                        new
                        {
                            Id = 31L,
                            Comment = "Test submission 31",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[11.48269882695,61.644714237]},\"properties\":{\"id\":31,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 31\",\"addedAt\":\"2024-10-02T19:05:27.3583957Z\",\"lastEdited\":\"2024-11-01T12:05:27.3583957Z\",\"radius\":325.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3031",
                            Status = "Uåpnet",
                            Timestamp = "2024-10-02T19:05:27.3583954Z"
                        },
                        new
                        {
                            Id = 32L,
                            Comment = "Test submission 32",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[11.595043950400001,61.762285664000004]},\"properties\":{\"id\":32,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 32\",\"addedAt\":\"2024-10-01T19:05:27.3583961Z\",\"lastEdited\":\"2024-11-01T11:05:27.3583962Z\",\"radius\":336}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3032",
                            Status = "Under arbeid",
                            Timestamp = "2024-10-01T19:05:27.3583959Z"
                        },
                        new
                        {
                            Id = 33L,
                            Comment = "Test submission 33",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[11.707389073849999,61.879857091]},\"properties\":{\"id\":33,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 33\",\"addedAt\":\"2024-09-30T19:05:27.3583967Z\",\"lastEdited\":\"2024-11-01T10:05:27.3583967Z\",\"radius\":346.5}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3033",
                            Status = "Akseptert",
                            Timestamp = "2024-09-30T19:05:27.3583964Z"
                        },
                        new
                        {
                            Id = 34L,
                            Comment = "Test submission 34",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[11.8197341973,61.997428518]},\"properties\":{\"id\":34,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 34\",\"addedAt\":\"2024-09-29T19:05:27.3583973Z\",\"lastEdited\":\"2024-11-01T09:05:27.3583974Z\",\"radius\":357}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3034",
                            Status = "Under arbeid",
                            Timestamp = "2024-09-29T19:05:27.3583970Z"
                        },
                        new
                        {
                            Id = 35L,
                            Comment = "Test submission 35",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[11.93207932075,62.114999945]},\"properties\":{\"id\":35,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 35\",\"addedAt\":\"2024-09-28T19:05:27.3584017Z\",\"lastEdited\":\"2024-11-01T08:05:27.3584018Z\",\"radius\":367.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3035",
                            Status = "Uåpnet",
                            Timestamp = "2024-09-28T19:05:27.3584014Z"
                        },
                        new
                        {
                            Id = 36L,
                            Comment = "Test submission 36",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[12.0444244442,62.232571372]},\"properties\":{\"id\":36,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 36\",\"addedAt\":\"2024-09-27T19:05:27.3584022Z\",\"lastEdited\":\"2024-11-01T07:05:27.3584023Z\",\"radius\":378}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3036",
                            Status = "Akseptert",
                            Timestamp = "2024-09-27T19:05:27.3584019Z"
                        },
                        new
                        {
                            Id = 37L,
                            Comment = "Test submission 37",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[12.156769567649999,62.350142799]},\"properties\":{\"id\":37,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 37\",\"addedAt\":\"2024-09-26T19:05:27.3584027Z\",\"lastEdited\":\"2024-11-01T06:05:27.3584028Z\",\"radius\":388.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3037",
                            Status = "Uåpnet",
                            Timestamp = "2024-09-26T19:05:27.3584024Z"
                        },
                        new
                        {
                            Id = 38L,
                            Comment = "Test submission 38",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[12.2691146911,62.467714226]},\"properties\":{\"id\":38,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 38\",\"addedAt\":\"2024-09-25T19:05:27.3584032Z\",\"lastEdited\":\"2024-11-01T05:05:27.3584033Z\",\"radius\":399}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3038",
                            Status = "Under arbeid",
                            Timestamp = "2024-09-25T19:05:27.3584030Z"
                        },
                        new
                        {
                            Id = 39L,
                            Comment = "Test submission 39",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[12.38145981455,62.585285653]},\"properties\":{\"id\":39,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 39\",\"addedAt\":\"2024-09-24T19:05:27.3584037Z\",\"lastEdited\":\"2024-11-01T04:05:27.3584038Z\",\"radius\":409.5}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3039",
                            Status = "Akseptert",
                            Timestamp = "2024-09-24T19:05:27.3584034Z"
                        },
                        new
                        {
                            Id = 40L,
                            Comment = "Test submission 40",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[12.493804938,62.70285708]},\"properties\":{\"id\":40,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 40\",\"addedAt\":\"2024-09-23T19:05:27.3584042Z\",\"lastEdited\":\"2024-11-01T03:05:27.3584043Z\",\"radius\":420}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3040",
                            Status = "Under arbeid",
                            Timestamp = "2024-09-23T19:05:27.3584040Z"
                        },
                        new
                        {
                            Id = 41L,
                            Comment = "Test submission 41",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[12.60615006145,62.820428507]},\"properties\":{\"id\":41,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 41\",\"addedAt\":\"2024-09-22T19:05:27.3584047Z\",\"lastEdited\":\"2024-11-01T02:05:27.3584048Z\",\"radius\":430.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3041",
                            Status = "Uåpnet",
                            Timestamp = "2024-09-22T19:05:27.3584044Z"
                        },
                        new
                        {
                            Id = 42L,
                            Comment = "Test submission 42",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[12.7184951849,62.937999934000004]},\"properties\":{\"id\":42,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 42\",\"addedAt\":\"2024-09-21T19:05:27.3584052Z\",\"lastEdited\":\"2024-11-01T01:05:27.3584053Z\",\"radius\":441}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3042",
                            Status = "Akseptert",
                            Timestamp = "2024-09-21T19:05:27.3584049Z"
                        },
                        new
                        {
                            Id = 43L,
                            Comment = "Test submission 43",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[12.83084030835,63.055571361]},\"properties\":{\"id\":43,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 43\",\"addedAt\":\"2024-09-20T19:05:27.3584057Z\",\"lastEdited\":\"2024-11-01T00:05:27.3584058Z\",\"radius\":451.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3043",
                            Status = "Uåpnet",
                            Timestamp = "2024-09-20T19:05:27.3584054Z"
                        },
                        new
                        {
                            Id = 44L,
                            Comment = "Test submission 44",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[12.9431854318,63.173142788]},\"properties\":{\"id\":44,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 44\",\"addedAt\":\"2024-09-19T19:05:27.3584062Z\",\"lastEdited\":\"2024-10-31T23:05:27.3584063Z\",\"radius\":462}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3044",
                            Status = "Under arbeid",
                            Timestamp = "2024-09-19T19:05:27.3584060Z"
                        },
                        new
                        {
                            Id = 45L,
                            Comment = "Test submission 45",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[13.05553055525,63.290714215]},\"properties\":{\"id\":45,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 45\",\"addedAt\":\"2024-09-18T19:05:27.3584094Z\",\"lastEdited\":\"2024-10-31T22:05:27.3584095Z\",\"radius\":472.5}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3045",
                            Status = "Akseptert",
                            Timestamp = "2024-09-18T19:05:27.3584091Z"
                        },
                        new
                        {
                            Id = 46L,
                            Comment = "Test submission 46",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[13.1678756787,63.408285642]},\"properties\":{\"id\":46,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 46\",\"addedAt\":\"2024-09-17T19:05:27.3584099Z\",\"lastEdited\":\"2024-10-31T21:05:27.3584100Z\",\"radius\":483}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3046",
                            Status = "Under arbeid",
                            Timestamp = "2024-09-17T19:05:27.3584097Z"
                        },
                        new
                        {
                            Id = 47L,
                            Comment = "Test submission 47",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[13.28022080215,63.525857069]},\"properties\":{\"id\":47,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 47\",\"addedAt\":\"2024-09-16T19:05:27.3584104Z\",\"lastEdited\":\"2024-10-31T20:05:27.3584105Z\",\"radius\":493.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3047",
                            Status = "Uåpnet",
                            Timestamp = "2024-09-16T19:05:27.3584102Z"
                        },
                        new
                        {
                            Id = 48L,
                            Comment = "Test submission 48",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[13.3925659256,63.643428496]},\"properties\":{\"id\":48,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 48\",\"addedAt\":\"2024-09-15T19:05:27.3584109Z\",\"lastEdited\":\"2024-10-31T19:05:27.3584110Z\",\"radius\":504}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3048",
                            Status = "Akseptert",
                            Timestamp = "2024-09-15T19:05:27.3584107Z"
                        },
                        new
                        {
                            Id = 49L,
                            Comment = "Test submission 49",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[13.504911049050001,63.760999923]},\"properties\":{\"id\":49,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 49\",\"addedAt\":\"2024-09-14T19:05:27.3584114Z\",\"lastEdited\":\"2024-10-31T18:05:27.3584115Z\",\"radius\":514.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3049",
                            Status = "Uåpnet",
                            Timestamp = "2024-09-14T19:05:27.3584112Z"
                        },
                        new
                        {
                            Id = 50L,
                            Comment = "Test submission 50",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[13.6172561725,63.87857135]},\"properties\":{\"id\":50,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 50\",\"addedAt\":\"2024-09-13T19:05:27.3584119Z\",\"lastEdited\":\"2024-10-31T17:05:27.3584120Z\",\"radius\":525}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3050",
                            Status = "Under arbeid",
                            Timestamp = "2024-09-13T19:05:27.3584117Z"
                        },
                        new
                        {
                            Id = 51L,
                            Comment = "Test submission 51",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[13.729601295950001,63.996142777]},\"properties\":{\"id\":51,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 51\",\"addedAt\":\"2024-09-12T19:05:27.3584124Z\",\"lastEdited\":\"2024-10-31T16:05:27.3584125Z\",\"radius\":535.5}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3051",
                            Status = "Akseptert",
                            Timestamp = "2024-09-12T19:05:27.3584121Z"
                        },
                        new
                        {
                            Id = 52L,
                            Comment = "Test submission 52",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[13.8419464194,64.113714204]},\"properties\":{\"id\":52,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 52\",\"addedAt\":\"2024-09-11T19:05:27.3584129Z\",\"lastEdited\":\"2024-10-31T15:05:27.3584130Z\",\"radius\":546}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3052",
                            Status = "Under arbeid",
                            Timestamp = "2024-09-11T19:05:27.3584126Z"
                        },
                        new
                        {
                            Id = 53L,
                            Comment = "Test submission 53",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[13.954291542850001,64.231285631]},\"properties\":{\"id\":53,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 53\",\"addedAt\":\"2024-09-10T19:05:27.3584134Z\",\"lastEdited\":\"2024-10-31T14:05:27.3584135Z\",\"radius\":556.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3053",
                            Status = "Uåpnet",
                            Timestamp = "2024-09-10T19:05:27.3584131Z"
                        },
                        new
                        {
                            Id = 54L,
                            Comment = "Test submission 54",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[14.066636666299999,64.348857058]},\"properties\":{\"id\":54,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 54\",\"addedAt\":\"2024-09-09T19:05:27.3584139Z\",\"lastEdited\":\"2024-10-31T13:05:27.3584140Z\",\"radius\":567}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3054",
                            Status = "Akseptert",
                            Timestamp = "2024-09-09T19:05:27.3584136Z"
                        },
                        new
                        {
                            Id = 55L,
                            Comment = "Test submission 55",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[14.17898178975,64.466428485]},\"properties\":{\"id\":55,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 55\",\"addedAt\":\"2024-09-08T19:05:27.3584170Z\",\"lastEdited\":\"2024-10-31T12:05:27.3584171Z\",\"radius\":577.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3055",
                            Status = "Uåpnet",
                            Timestamp = "2024-09-08T19:05:27.3584141Z"
                        },
                        new
                        {
                            Id = 56L,
                            Comment = "Test submission 56",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[14.291326913199999,64.583999912]},\"properties\":{\"id\":56,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 56\",\"addedAt\":\"2024-09-07T19:05:27.3584175Z\",\"lastEdited\":\"2024-10-31T11:05:27.3584176Z\",\"radius\":588}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3056",
                            Status = "Under arbeid",
                            Timestamp = "2024-09-07T19:05:27.3584173Z"
                        },
                        new
                        {
                            Id = 57L,
                            Comment = "Test submission 57",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[14.40367203665,64.701571339]},\"properties\":{\"id\":57,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 57\",\"addedAt\":\"2024-09-06T19:05:27.3584181Z\",\"lastEdited\":\"2024-10-31T10:05:27.3584181Z\",\"radius\":598.5}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3057",
                            Status = "Akseptert",
                            Timestamp = "2024-09-06T19:05:27.3584178Z"
                        },
                        new
                        {
                            Id = 58L,
                            Comment = "Test submission 58",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[14.516017160099999,64.819142766]},\"properties\":{\"id\":58,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 58\",\"addedAt\":\"2024-09-05T19:05:27.3584186Z\",\"lastEdited\":\"2024-10-31T09:05:27.3584186Z\",\"radius\":609}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3058",
                            Status = "Under arbeid",
                            Timestamp = "2024-09-05T19:05:27.3584183Z"
                        },
                        new
                        {
                            Id = 59L,
                            Comment = "Test submission 59",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[14.62836228355,64.936714193]},\"properties\":{\"id\":59,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 59\",\"addedAt\":\"2024-09-04T19:05:27.3584191Z\",\"lastEdited\":\"2024-10-31T08:05:27.3584191Z\",\"radius\":619.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3059",
                            Status = "Uåpnet",
                            Timestamp = "2024-09-04T19:05:27.3584188Z"
                        },
                        new
                        {
                            Id = 60L,
                            Comment = "Test submission 60",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[14.740707407,65.05428562]},\"properties\":{\"id\":60,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 60\",\"addedAt\":\"2024-09-03T19:05:27.3584196Z\",\"lastEdited\":\"2024-10-31T07:05:27.3584197Z\",\"radius\":630}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3060",
                            Status = "Akseptert",
                            Timestamp = "2024-09-03T19:05:27.3584193Z"
                        },
                        new
                        {
                            Id = 61L,
                            Comment = "Test submission 61",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[14.85305253045,65.171857047]},\"properties\":{\"id\":61,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 61\",\"addedAt\":\"2024-09-02T19:05:27.3584201Z\",\"lastEdited\":\"2024-10-31T06:05:27.3584202Z\",\"radius\":640.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3061",
                            Status = "Uåpnet",
                            Timestamp = "2024-09-02T19:05:27.3584198Z"
                        },
                        new
                        {
                            Id = 62L,
                            Comment = "Test submission 62",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[14.9653976539,65.289428474]},\"properties\":{\"id\":62,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 62\",\"addedAt\":\"2024-09-01T19:05:27.3584206Z\",\"lastEdited\":\"2024-10-31T05:05:27.3584206Z\",\"radius\":651}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3062",
                            Status = "Under arbeid",
                            Timestamp = "2024-09-01T19:05:27.3584203Z"
                        },
                        new
                        {
                            Id = 63L,
                            Comment = "Test submission 63",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[15.07774277735,65.406999901]},\"properties\":{\"id\":63,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 63\",\"addedAt\":\"2024-08-31T19:05:27.3584211Z\",\"lastEdited\":\"2024-10-31T04:05:27.3584211Z\",\"radius\":661.5}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3063",
                            Status = "Akseptert",
                            Timestamp = "2024-08-31T19:05:27.3584208Z"
                        },
                        new
                        {
                            Id = 64L,
                            Comment = "Test submission 64",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[15.1900879008,65.52457132800001]},\"properties\":{\"id\":64,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 64\",\"addedAt\":\"2024-08-30T19:05:27.3584216Z\",\"lastEdited\":\"2024-10-31T03:05:27.3584216Z\",\"radius\":672}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3064",
                            Status = "Under arbeid",
                            Timestamp = "2024-08-30T19:05:27.3584213Z"
                        },
                        new
                        {
                            Id = 65L,
                            Comment = "Test submission 65",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[15.30243302425,65.642142755]},\"properties\":{\"id\":65,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 65\",\"addedAt\":\"2024-08-29T19:05:27.3584246Z\",\"lastEdited\":\"2024-10-31T02:05:27.3584247Z\",\"radius\":682.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3065",
                            Status = "Uåpnet",
                            Timestamp = "2024-08-29T19:05:27.3584218Z"
                        },
                        new
                        {
                            Id = 66L,
                            Comment = "Test submission 66",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[15.4147781477,65.759714182]},\"properties\":{\"id\":66,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 66\",\"addedAt\":\"2024-08-28T19:05:27.3584253Z\",\"lastEdited\":\"2024-10-31T01:05:27.3584254Z\",\"radius\":693}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3066",
                            Status = "Akseptert",
                            Timestamp = "2024-08-28T19:05:27.3584250Z"
                        },
                        new
                        {
                            Id = 67L,
                            Comment = "Test submission 67",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[15.52712327115,65.877285609]},\"properties\":{\"id\":67,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 67\",\"addedAt\":\"2024-08-27T19:05:27.3584258Z\",\"lastEdited\":\"2024-10-31T00:05:27.3584259Z\",\"radius\":703.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3067",
                            Status = "Uåpnet",
                            Timestamp = "2024-08-27T19:05:27.3584255Z"
                        },
                        new
                        {
                            Id = 68L,
                            Comment = "Test submission 68",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[15.6394683946,65.994857036]},\"properties\":{\"id\":68,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 68\",\"addedAt\":\"2024-08-26T19:05:27.3584263Z\",\"lastEdited\":\"2024-10-30T23:05:27.3584264Z\",\"radius\":714}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3068",
                            Status = "Under arbeid",
                            Timestamp = "2024-08-26T19:05:27.3584260Z"
                        },
                        new
                        {
                            Id = 69L,
                            Comment = "Test submission 69",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[15.75181351805,66.112428463]},\"properties\":{\"id\":69,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 69\",\"addedAt\":\"2024-08-25T19:05:27.3584268Z\",\"lastEdited\":\"2024-10-30T22:05:27.3584269Z\",\"radius\":724.5}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3069",
                            Status = "Akseptert",
                            Timestamp = "2024-08-25T19:05:27.3584265Z"
                        },
                        new
                        {
                            Id = 70L,
                            Comment = "Test submission 70",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[15.864158641500001,66.22999989]},\"properties\":{\"id\":70,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 70\",\"addedAt\":\"2024-08-24T19:05:27.3584273Z\",\"lastEdited\":\"2024-10-30T21:05:27.3584273Z\",\"radius\":735}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3070",
                            Status = "Under arbeid",
                            Timestamp = "2024-08-24T19:05:27.3584270Z"
                        },
                        new
                        {
                            Id = 71L,
                            Comment = "Test submission 71",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[15.97650376495,66.347571317]},\"properties\":{\"id\":71,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 71\",\"addedAt\":\"2024-08-23T19:05:27.3584278Z\",\"lastEdited\":\"2024-10-30T20:05:27.3584278Z\",\"radius\":745.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3071",
                            Status = "Uåpnet",
                            Timestamp = "2024-08-23T19:05:27.3584275Z"
                        },
                        new
                        {
                            Id = 72L,
                            Comment = "Test submission 72",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[16.0888488884,66.465142744]},\"properties\":{\"id\":72,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 72\",\"addedAt\":\"2024-08-22T19:05:27.3584283Z\",\"lastEdited\":\"2024-10-30T19:05:27.3584283Z\",\"radius\":756}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3072",
                            Status = "Akseptert",
                            Timestamp = "2024-08-22T19:05:27.3584280Z"
                        },
                        new
                        {
                            Id = 73L,
                            Comment = "Test submission 73",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[16.20119401185,66.582714171]},\"properties\":{\"id\":73,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 73\",\"addedAt\":\"2024-08-21T19:05:27.3584288Z\",\"lastEdited\":\"2024-10-30T18:05:27.3584289Z\",\"radius\":766.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3073",
                            Status = "Uåpnet",
                            Timestamp = "2024-08-21T19:05:27.3584285Z"
                        },
                        new
                        {
                            Id = 74L,
                            Comment = "Test submission 74",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[16.313539135299997,66.700285598]},\"properties\":{\"id\":74,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 74\",\"addedAt\":\"2024-08-20T19:05:27.3584319Z\",\"lastEdited\":\"2024-10-30T17:05:27.3584320Z\",\"radius\":777}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3074",
                            Status = "Under arbeid",
                            Timestamp = "2024-08-20T19:05:27.3584290Z"
                        },
                        new
                        {
                            Id = 75L,
                            Comment = "Test submission 75",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[16.425884258750003,66.817857025]},\"properties\":{\"id\":75,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 75\",\"addedAt\":\"2024-08-19T19:05:27.3584325Z\",\"lastEdited\":\"2024-10-30T16:05:27.3584325Z\",\"radius\":787.5}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3075",
                            Status = "Akseptert",
                            Timestamp = "2024-08-19T19:05:27.3584322Z"
                        },
                        new
                        {
                            Id = 76L,
                            Comment = "Test submission 76",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[16.5382293822,66.935428452]},\"properties\":{\"id\":76,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 76\",\"addedAt\":\"2024-08-18T19:05:27.3584329Z\",\"lastEdited\":\"2024-10-30T15:05:27.3584330Z\",\"radius\":798}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3076",
                            Status = "Under arbeid",
                            Timestamp = "2024-08-18T19:05:27.3584327Z"
                        },
                        new
                        {
                            Id = 77L,
                            Comment = "Test submission 77",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[16.65057450565,67.052999879]},\"properties\":{\"id\":77,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 77\",\"addedAt\":\"2024-08-17T19:05:27.3584335Z\",\"lastEdited\":\"2024-10-30T14:05:27.3584335Z\",\"radius\":808.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3077",
                            Status = "Uåpnet",
                            Timestamp = "2024-08-17T19:05:27.3584332Z"
                        },
                        new
                        {
                            Id = 78L,
                            Comment = "Test submission 78",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[16.7629196291,67.170571306]},\"properties\":{\"id\":78,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 78\",\"addedAt\":\"2024-08-16T19:05:27.3584340Z\",\"lastEdited\":\"2024-10-30T13:05:27.3584340Z\",\"radius\":819}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3078",
                            Status = "Akseptert",
                            Timestamp = "2024-08-16T19:05:27.3584337Z"
                        },
                        new
                        {
                            Id = 79L,
                            Comment = "Test submission 79",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[16.875264752550002,67.288142733]},\"properties\":{\"id\":79,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 79\",\"addedAt\":\"2024-08-15T19:05:27.3584345Z\",\"lastEdited\":\"2024-10-30T12:05:27.3584345Z\",\"radius\":829.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3079",
                            Status = "Uåpnet",
                            Timestamp = "2024-08-15T19:05:27.3584342Z"
                        },
                        new
                        {
                            Id = 80L,
                            Comment = "Test submission 80",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[16.987609876,67.40571416]},\"properties\":{\"id\":80,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 80\",\"addedAt\":\"2024-08-14T19:05:27.3584349Z\",\"lastEdited\":\"2024-10-30T11:05:27.3584350Z\",\"radius\":840}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3080",
                            Status = "Under arbeid",
                            Timestamp = "2024-08-14T19:05:27.3584347Z"
                        },
                        new
                        {
                            Id = 81L,
                            Comment = "Test submission 81",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[17.09995499945,67.523285587]},\"properties\":{\"id\":81,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 81\",\"addedAt\":\"2024-08-13T19:05:27.3584354Z\",\"lastEdited\":\"2024-10-30T10:05:27.3584355Z\",\"radius\":850.5}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3081",
                            Status = "Akseptert",
                            Timestamp = "2024-08-13T19:05:27.3584352Z"
                        },
                        new
                        {
                            Id = 82L,
                            Comment = "Test submission 82",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[17.2123001229,67.640857014]},\"properties\":{\"id\":82,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 82\",\"addedAt\":\"2024-08-12T19:05:27.3584359Z\",\"lastEdited\":\"2024-10-30T09:05:27.3584360Z\",\"radius\":861}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3082",
                            Status = "Under arbeid",
                            Timestamp = "2024-08-12T19:05:27.3584357Z"
                        },
                        new
                        {
                            Id = 83L,
                            Comment = "Test submission 83",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[17.324645246350002,67.758428441]},\"properties\":{\"id\":83,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 83\",\"addedAt\":\"2024-08-11T19:05:27.3584364Z\",\"lastEdited\":\"2024-10-30T08:05:27.3584365Z\",\"radius\":871.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3083",
                            Status = "Uåpnet",
                            Timestamp = "2024-08-11T19:05:27.3584362Z"
                        },
                        new
                        {
                            Id = 84L,
                            Comment = "Test submission 84",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[17.4369903698,67.87599986800001]},\"properties\":{\"id\":84,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 84\",\"addedAt\":\"2024-08-10T19:05:27.3584394Z\",\"lastEdited\":\"2024-10-30T07:05:27.3584395Z\",\"radius\":882}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3084",
                            Status = "Akseptert",
                            Timestamp = "2024-08-10T19:05:27.3584367Z"
                        },
                        new
                        {
                            Id = 85L,
                            Comment = "Test submission 85",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[17.54933549325,67.993571295]},\"properties\":{\"id\":85,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 85\",\"addedAt\":\"2024-08-09T19:05:27.3584399Z\",\"lastEdited\":\"2024-10-30T06:05:27.3584400Z\",\"radius\":892.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3085",
                            Status = "Uåpnet",
                            Timestamp = "2024-08-09T19:05:27.3584397Z"
                        },
                        new
                        {
                            Id = 86L,
                            Comment = "Test submission 86",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[17.6616806167,68.111142722]},\"properties\":{\"id\":86,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 86\",\"addedAt\":\"2024-08-08T19:05:27.3584404Z\",\"lastEdited\":\"2024-10-30T05:05:27.3584405Z\",\"radius\":903}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3086",
                            Status = "Under arbeid",
                            Timestamp = "2024-08-08T19:05:27.3584401Z"
                        },
                        new
                        {
                            Id = 87L,
                            Comment = "Test submission 87",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[17.77402574015,68.228714149]},\"properties\":{\"id\":87,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 87\",\"addedAt\":\"2024-08-07T19:05:27.3584409Z\",\"lastEdited\":\"2024-10-30T04:05:27.3584410Z\",\"radius\":913.5}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3087",
                            Status = "Akseptert",
                            Timestamp = "2024-08-07T19:05:27.3584406Z"
                        },
                        new
                        {
                            Id = 88L,
                            Comment = "Test submission 88",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[17.8863708636,68.346285576]},\"properties\":{\"id\":88,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 88\",\"addedAt\":\"2024-08-06T19:05:27.3584414Z\",\"lastEdited\":\"2024-10-30T03:05:27.3584415Z\",\"radius\":924}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3088",
                            Status = "Under arbeid",
                            Timestamp = "2024-08-06T19:05:27.3584411Z"
                        },
                        new
                        {
                            Id = 89L,
                            Comment = "Test submission 89",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[17.998715987049998,68.463857003]},\"properties\":{\"id\":89,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 89\",\"addedAt\":\"2024-08-05T19:05:27.3584419Z\",\"lastEdited\":\"2024-10-30T02:05:27.3584420Z\",\"radius\":934.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3089",
                            Status = "Uåpnet",
                            Timestamp = "2024-08-05T19:05:27.3584417Z"
                        },
                        new
                        {
                            Id = 90L,
                            Comment = "Test submission 90",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[18.1110611105,68.58142843]},\"properties\":{\"id\":90,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 90\",\"addedAt\":\"2024-08-04T19:05:27.3584425Z\",\"lastEdited\":\"2024-10-30T01:05:27.3584425Z\",\"radius\":945}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3090",
                            Status = "Akseptert",
                            Timestamp = "2024-08-04T19:05:27.3584422Z"
                        },
                        new
                        {
                            Id = 91L,
                            Comment = "Test submission 91",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[18.22340623395,68.698999857]},\"properties\":{\"id\":91,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 91\",\"addedAt\":\"2024-08-03T19:05:27.3584430Z\",\"lastEdited\":\"2024-10-30T00:05:27.3584430Z\",\"radius\":955.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3091",
                            Status = "Uåpnet",
                            Timestamp = "2024-08-03T19:05:27.3584427Z"
                        },
                        new
                        {
                            Id = 92L,
                            Comment = "Test submission 92",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[18.3357513574,68.816571284]},\"properties\":{\"id\":92,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 92\",\"addedAt\":\"2024-08-02T19:05:27.3584435Z\",\"lastEdited\":\"2024-10-29T23:05:27.3584435Z\",\"radius\":966}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3092",
                            Status = "Under arbeid",
                            Timestamp = "2024-08-02T19:05:27.3584432Z"
                        },
                        new
                        {
                            Id = 93L,
                            Comment = "Test submission 93",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[18.448096480849998,68.93414271099999]},\"properties\":{\"id\":93,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 93\",\"addedAt\":\"2024-08-01T19:05:27.3584440Z\",\"lastEdited\":\"2024-10-29T22:05:27.3584441Z\",\"radius\":976.5}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3093",
                            Status = "Akseptert",
                            Timestamp = "2024-08-01T19:05:27.3584437Z"
                        },
                        new
                        {
                            Id = 94L,
                            Comment = "Test submission 94",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[18.5604416043,69.051714138]},\"properties\":{\"id\":94,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 94\",\"addedAt\":\"2024-07-31T19:05:27.3584463Z\",\"lastEdited\":\"2024-10-29T21:05:27.3584464Z\",\"radius\":987}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3094",
                            Status = "Under arbeid",
                            Timestamp = "2024-07-31T19:05:27.3584442Z"
                        },
                        new
                        {
                            Id = 95L,
                            Comment = "Test submission 95",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[18.67278672775,69.169285565]},\"properties\":{\"id\":95,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 95\",\"addedAt\":\"2024-07-30T19:05:27.3584469Z\",\"lastEdited\":\"2024-10-29T20:05:27.3584470Z\",\"radius\":997.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3095",
                            Status = "Uåpnet",
                            Timestamp = "2024-07-30T19:05:27.3584466Z"
                        },
                        new
                        {
                            Id = 96L,
                            Comment = "Test submission 96",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[18.7851318512,69.286856992]},\"properties\":{\"id\":96,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 96\",\"addedAt\":\"2024-07-29T19:05:27.3584474Z\",\"lastEdited\":\"2024-10-29T19:05:27.3584475Z\",\"radius\":1008}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3096",
                            Status = "Akseptert",
                            Timestamp = "2024-07-29T19:05:27.3584472Z"
                        },
                        new
                        {
                            Id = 97L,
                            Comment = "Test submission 97",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[18.89747697465,69.404428419]},\"properties\":{\"id\":97,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 97\",\"addedAt\":\"2024-07-28T19:05:27.3584479Z\",\"lastEdited\":\"2024-10-29T18:05:27.3584480Z\",\"radius\":1018.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3097",
                            Status = "Uåpnet",
                            Timestamp = "2024-07-28T19:05:27.3584477Z"
                        },
                        new
                        {
                            Id = 98L,
                            Comment = "Test submission 98",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[19.009822098100003,69.521999846]},\"properties\":{\"id\":98,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 98\",\"addedAt\":\"2024-07-27T19:05:27.3584484Z\",\"lastEdited\":\"2024-10-29T17:05:27.3584485Z\",\"radius\":1029}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3098",
                            Status = "Under arbeid",
                            Timestamp = "2024-07-27T19:05:27.3584482Z"
                        },
                        new
                        {
                            Id = 99L,
                            Comment = "Test submission 99",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[19.12216722155,69.639571273]},\"properties\":{\"id\":99,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 99\",\"addedAt\":\"2024-07-26T19:05:27.3584489Z\",\"lastEdited\":\"2024-10-29T16:05:27.3584490Z\",\"radius\":1039.5}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3099",
                            Status = "Akseptert",
                            Timestamp = "2024-07-26T19:05:27.3584487Z"
                        },
                        new
                        {
                            Id = 100L,
                            Comment = "Test submission 100",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[19.234512345,69.7571427]},\"properties\":{\"id\":100,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 100\",\"addedAt\":\"2024-07-25T19:05:27.3584495Z\",\"lastEdited\":\"2024-10-29T15:05:27.3584495Z\",\"radius\":1050}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3100",
                            Status = "Under arbeid",
                            Timestamp = "2024-07-25T19:05:27.3584492Z"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
