// <auto-generated />
using System;
using Kartverket_group2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kartverket_group2.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241106143056_TieUserIDToSubmission")]
    partial class TieUserIDToSubmission
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Kartverket_group2.Models.ApplicationUserModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Kartverket_group2.Models.Submission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "comment");

                    b.Property<string>("GeoJsonData")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "geoJsonData");

                    b.Property<string>("Municipalitynr")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "municipalitynr");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "status");

                    b.Property<string>("Timestamp")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "timestamp");

                    b.Property<string>("UserId")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Submissions");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Comment = "Test submission 1",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[8.11234,58.11757]},\"properties\":{\"id\":1,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 1\",\"addedAt\":\"2024-11-05T14:30:55.6523197Z\",\"lastEdited\":\"2024-11-06T13:30:55.6523199Z\",\"radius\":10.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3001",
                            Status = "Uåpnet",
                            Timestamp = "2024-11-05T14:30:55.6523170Z"
                        },
                        new
                        {
                            Id = 2L,
                            Comment = "Test submission 2",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[8.22468,58.23514]},\"properties\":{\"id\":2,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 2\",\"addedAt\":\"2024-11-04T14:30:55.6523212Z\",\"lastEdited\":\"2024-11-06T12:30:55.6523212Z\",\"radius\":21}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3002",
                            Status = "Under arbeid",
                            Timestamp = "2024-11-04T14:30:55.6523208Z"
                        },
                        new
                        {
                            Id = 3L,
                            Comment = "Test submission 3",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[8.33702,58.35271]},\"properties\":{\"id\":3,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 3\",\"addedAt\":\"2024-11-03T14:30:55.6523218Z\",\"lastEdited\":\"2024-11-06T11:30:55.6523218Z\",\"radius\":31.5}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3003",
                            Status = "Akseptert",
                            Timestamp = "2024-11-03T14:30:55.6523215Z"
                        },
                        new
                        {
                            Id = 4L,
                            Comment = "Test submission 4",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[8.44936,58.47028]},\"properties\":{\"id\":4,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 4\",\"addedAt\":\"2024-11-02T14:30:55.6523260Z\",\"lastEdited\":\"2024-11-06T10:30:55.6523260Z\",\"radius\":42}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3004",
                            Status = "Under arbeid",
                            Timestamp = "2024-11-02T14:30:55.6523256Z"
                        },
                        new
                        {
                            Id = 5L,
                            Comment = "Test submission 5",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[8.5617,58.58785]},\"properties\":{\"id\":5,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 5\",\"addedAt\":\"2024-11-01T14:30:55.6523265Z\",\"lastEdited\":\"2024-11-06T09:30:55.6523266Z\",\"radius\":52.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3005",
                            Status = "Uåpnet",
                            Timestamp = "2024-11-01T14:30:55.6523263Z"
                        },
                        new
                        {
                            Id = 6L,
                            Comment = "Test submission 6",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[8.67404,58.70542]},\"properties\":{\"id\":6,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 6\",\"addedAt\":\"2024-10-31T14:30:55.6523272Z\",\"lastEdited\":\"2024-11-06T08:30:55.6523273Z\",\"radius\":63}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3006",
                            Status = "Akseptert",
                            Timestamp = "2024-10-31T14:30:55.6523269Z"
                        },
                        new
                        {
                            Id = 7L,
                            Comment = "Test submission 7",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[8.78638,58.82299]},\"properties\":{\"id\":7,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 7\",\"addedAt\":\"2024-10-30T14:30:55.6523277Z\",\"lastEdited\":\"2024-11-06T07:30:55.6523278Z\",\"radius\":73.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3007",
                            Status = "Uåpnet",
                            Timestamp = "2024-10-30T14:30:55.6523275Z"
                        },
                        new
                        {
                            Id = 8L,
                            Comment = "Test submission 8",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[8.89872,58.94056]},\"properties\":{\"id\":8,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 8\",\"addedAt\":\"2024-10-29T14:30:55.6523283Z\",\"lastEdited\":\"2024-11-06T06:30:55.6523283Z\",\"radius\":84}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3008",
                            Status = "Under arbeid",
                            Timestamp = "2024-10-29T14:30:55.6523280Z"
                        },
                        new
                        {
                            Id = 9L,
                            Comment = "Test submission 9",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[9.01106,59.05813]},\"properties\":{\"id\":9,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 9\",\"addedAt\":\"2024-10-28T14:30:55.6523288Z\",\"lastEdited\":\"2024-11-06T05:30:55.6523289Z\",\"radius\":94.5}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3009",
                            Status = "Akseptert",
                            Timestamp = "2024-10-28T14:30:55.6523285Z"
                        },
                        new
                        {
                            Id = 10L,
                            Comment = "Test submission 10",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[9.1234,59.1757]},\"properties\":{\"id\":10,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 10\",\"addedAt\":\"2024-10-27T14:30:55.6523294Z\",\"lastEdited\":\"2024-11-06T04:30:55.6523295Z\",\"radius\":105}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3010",
                            Status = "Under arbeid",
                            Timestamp = "2024-10-27T14:30:55.6523291Z"
                        },
                        new
                        {
                            Id = 11L,
                            Comment = "Test submission 11",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[9.23574,59.29327]},\"properties\":{\"id\":11,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 11\",\"addedAt\":\"2024-10-26T14:30:55.6523299Z\",\"lastEdited\":\"2024-11-06T03:30:55.6523300Z\",\"radius\":115.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3011",
                            Status = "Uåpnet",
                            Timestamp = "2024-10-26T14:30:55.6523296Z"
                        },
                        new
                        {
                            Id = 12L,
                            Comment = "Test submission 12",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[9.34808,59.41084]},\"properties\":{\"id\":12,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 12\",\"addedAt\":\"2024-10-25T14:30:55.6523304Z\",\"lastEdited\":\"2024-11-06T02:30:55.6523305Z\",\"radius\":126}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3012",
                            Status = "Akseptert",
                            Timestamp = "2024-10-25T14:30:55.6523302Z"
                        },
                        new
                        {
                            Id = 13L,
                            Comment = "Test submission 13",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[9.46042,59.52841]},\"properties\":{\"id\":13,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 13\",\"addedAt\":\"2024-10-24T14:30:55.6523310Z\",\"lastEdited\":\"2024-11-06T01:30:55.6523310Z\",\"radius\":136.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3013",
                            Status = "Uåpnet",
                            Timestamp = "2024-10-24T14:30:55.6523307Z"
                        },
                        new
                        {
                            Id = 14L,
                            Comment = "Test submission 14",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[9.57276,59.64598]},\"properties\":{\"id\":14,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 14\",\"addedAt\":\"2024-10-23T14:30:55.6523343Z\",\"lastEdited\":\"2024-11-06T00:30:55.6523344Z\",\"radius\":147}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3014",
                            Status = "Under arbeid",
                            Timestamp = "2024-10-23T14:30:55.6523340Z"
                        },
                        new
                        {
                            Id = 15L,
                            Comment = "Test submission 15",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[9.6851,59.76355]},\"properties\":{\"id\":15,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 15\",\"addedAt\":\"2024-10-22T14:30:55.6523349Z\",\"lastEdited\":\"2024-11-05T23:30:55.6523349Z\",\"radius\":157.5}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3015",
                            Status = "Akseptert",
                            Timestamp = "2024-10-22T14:30:55.6523346Z"
                        },
                        new
                        {
                            Id = 16L,
                            Comment = "Test submission 16",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[9.79744,59.88112]},\"properties\":{\"id\":16,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 16\",\"addedAt\":\"2024-10-21T14:30:55.6523354Z\",\"lastEdited\":\"2024-11-05T22:30:55.6523354Z\",\"radius\":168}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3016",
                            Status = "Under arbeid",
                            Timestamp = "2024-10-21T14:30:55.6523351Z"
                        },
                        new
                        {
                            Id = 17L,
                            Comment = "Test submission 17",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[9.90978,59.998689999999996]},\"properties\":{\"id\":17,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 17\",\"addedAt\":\"2024-10-20T14:30:55.6523359Z\",\"lastEdited\":\"2024-11-05T21:30:55.6523360Z\",\"radius\":178.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3017",
                            Status = "Uåpnet",
                            Timestamp = "2024-10-20T14:30:55.6523356Z"
                        },
                        new
                        {
                            Id = 18L,
                            Comment = "Test submission 18",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[10.022120000000001,60.11626]},\"properties\":{\"id\":18,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 18\",\"addedAt\":\"2024-10-19T14:30:55.6523365Z\",\"lastEdited\":\"2024-11-05T20:30:55.6523366Z\",\"radius\":189}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3018",
                            Status = "Akseptert",
                            Timestamp = "2024-10-19T14:30:55.6523362Z"
                        },
                        new
                        {
                            Id = 19L,
                            Comment = "Test submission 19",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[10.13446,60.23383]},\"properties\":{\"id\":19,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 19\",\"addedAt\":\"2024-10-18T14:30:55.6523370Z\",\"lastEdited\":\"2024-11-05T19:30:55.6523371Z\",\"radius\":199.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3019",
                            Status = "Uåpnet",
                            Timestamp = "2024-10-18T14:30:55.6523367Z"
                        },
                        new
                        {
                            Id = 20L,
                            Comment = "Test submission 20",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[10.2468,60.3514]},\"properties\":{\"id\":20,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 20\",\"addedAt\":\"2024-10-17T14:30:55.6523375Z\",\"lastEdited\":\"2024-11-05T18:30:55.6523376Z\",\"radius\":210}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3020",
                            Status = "Under arbeid",
                            Timestamp = "2024-10-17T14:30:55.6523373Z"
                        },
                        new
                        {
                            Id = 21L,
                            Comment = "Test submission 21",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[10.35914,60.46897]},\"properties\":{\"id\":21,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 21\",\"addedAt\":\"2024-10-16T14:30:55.6523381Z\",\"lastEdited\":\"2024-11-05T17:30:55.6523381Z\",\"radius\":220.5}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3021",
                            Status = "Akseptert",
                            Timestamp = "2024-10-16T14:30:55.6523378Z"
                        },
                        new
                        {
                            Id = 22L,
                            Comment = "Test submission 22",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[10.47148,60.58654]},\"properties\":{\"id\":22,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 22\",\"addedAt\":\"2024-10-15T14:30:55.6523386Z\",\"lastEdited\":\"2024-11-05T16:30:55.6523387Z\",\"radius\":231}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3022",
                            Status = "Under arbeid",
                            Timestamp = "2024-10-15T14:30:55.6523383Z"
                        },
                        new
                        {
                            Id = 23L,
                            Comment = "Test submission 23",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[10.58382,60.70411]},\"properties\":{\"id\":23,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 23\",\"addedAt\":\"2024-10-14T14:30:55.6523417Z\",\"lastEdited\":\"2024-11-05T15:30:55.6523418Z\",\"radius\":241.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3023",
                            Status = "Uåpnet",
                            Timestamp = "2024-10-14T14:30:55.6523388Z"
                        },
                        new
                        {
                            Id = 24L,
                            Comment = "Test submission 24",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[10.696159999999999,60.82168]},\"properties\":{\"id\":24,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 24\",\"addedAt\":\"2024-10-13T14:30:55.6523422Z\",\"lastEdited\":\"2024-11-05T14:30:55.6523423Z\",\"radius\":252}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3024",
                            Status = "Akseptert",
                            Timestamp = "2024-10-13T14:30:55.6523420Z"
                        },
                        new
                        {
                            Id = 25L,
                            Comment = "Test submission 25",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[10.8085,60.93925]},\"properties\":{\"id\":25,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 25\",\"addedAt\":\"2024-10-12T14:30:55.6523428Z\",\"lastEdited\":\"2024-11-05T13:30:55.6523428Z\",\"radius\":262.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3025",
                            Status = "Uåpnet",
                            Timestamp = "2024-10-12T14:30:55.6523425Z"
                        },
                        new
                        {
                            Id = 26L,
                            Comment = "Test submission 26",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[10.92084,61.05682]},\"properties\":{\"id\":26,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 26\",\"addedAt\":\"2024-10-11T14:30:55.6523433Z\",\"lastEdited\":\"2024-11-05T12:30:55.6523434Z\",\"radius\":273}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3026",
                            Status = "Under arbeid",
                            Timestamp = "2024-10-11T14:30:55.6523430Z"
                        },
                        new
                        {
                            Id = 27L,
                            Comment = "Test submission 27",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[11.03318,61.17439]},\"properties\":{\"id\":27,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 27\",\"addedAt\":\"2024-10-10T14:30:55.6523438Z\",\"lastEdited\":\"2024-11-05T11:30:55.6523439Z\",\"radius\":283.5}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3027",
                            Status = "Akseptert",
                            Timestamp = "2024-10-10T14:30:55.6523436Z"
                        },
                        new
                        {
                            Id = 28L,
                            Comment = "Test submission 28",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[11.14552,61.29196]},\"properties\":{\"id\":28,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 28\",\"addedAt\":\"2024-10-09T14:30:55.6523443Z\",\"lastEdited\":\"2024-11-05T10:30:55.6523444Z\",\"radius\":294}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3028",
                            Status = "Under arbeid",
                            Timestamp = "2024-10-09T14:30:55.6523441Z"
                        },
                        new
                        {
                            Id = 29L,
                            Comment = "Test submission 29",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[11.25786,61.40953]},\"properties\":{\"id\":29,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 29\",\"addedAt\":\"2024-10-08T14:30:55.6523449Z\",\"lastEdited\":\"2024-11-05T09:30:55.6523449Z\",\"radius\":304.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3029",
                            Status = "Uåpnet",
                            Timestamp = "2024-10-08T14:30:55.6523446Z"
                        },
                        new
                        {
                            Id = 30L,
                            Comment = "Test submission 30",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[11.3702,61.5271]},\"properties\":{\"id\":30,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 30\",\"addedAt\":\"2024-10-07T14:30:55.6523454Z\",\"lastEdited\":\"2024-11-05T08:30:55.6523455Z\",\"radius\":315}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3030",
                            Status = "Akseptert",
                            Timestamp = "2024-10-07T14:30:55.6523451Z"
                        },
                        new
                        {
                            Id = 31L,
                            Comment = "Test submission 31",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[11.48254,61.64467]},\"properties\":{\"id\":31,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 31\",\"addedAt\":\"2024-10-06T14:30:55.6523459Z\",\"lastEdited\":\"2024-11-05T07:30:55.6523460Z\",\"radius\":325.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3031",
                            Status = "Uåpnet",
                            Timestamp = "2024-10-06T14:30:55.6523456Z"
                        },
                        new
                        {
                            Id = 32L,
                            Comment = "Test submission 32",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[11.59488,61.76224]},\"properties\":{\"id\":32,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 32\",\"addedAt\":\"2024-10-05T14:30:55.6523464Z\",\"lastEdited\":\"2024-11-05T06:30:55.6523465Z\",\"radius\":336}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3032",
                            Status = "Under arbeid",
                            Timestamp = "2024-10-05T14:30:55.6523462Z"
                        },
                        new
                        {
                            Id = 33L,
                            Comment = "Test submission 33",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[11.70722,61.87981]},\"properties\":{\"id\":33,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 33\",\"addedAt\":\"2024-10-04T14:30:55.6523469Z\",\"lastEdited\":\"2024-11-05T05:30:55.6523486Z\",\"radius\":346.5}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3033",
                            Status = "Akseptert",
                            Timestamp = "2024-10-04T14:30:55.6523467Z"
                        },
                        new
                        {
                            Id = 34L,
                            Comment = "Test submission 34",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[11.81956,61.99738]},\"properties\":{\"id\":34,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 34\",\"addedAt\":\"2024-10-03T14:30:55.6523492Z\",\"lastEdited\":\"2024-11-05T04:30:55.6523493Z\",\"radius\":357}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3034",
                            Status = "Under arbeid",
                            Timestamp = "2024-10-03T14:30:55.6523489Z"
                        },
                        new
                        {
                            Id = 35L,
                            Comment = "Test submission 35",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[11.931899999999999,62.11495]},\"properties\":{\"id\":35,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 35\",\"addedAt\":\"2024-10-02T14:30:55.6523498Z\",\"lastEdited\":\"2024-11-05T03:30:55.6523498Z\",\"radius\":367.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3035",
                            Status = "Uåpnet",
                            Timestamp = "2024-10-02T14:30:55.6523495Z"
                        },
                        new
                        {
                            Id = 36L,
                            Comment = "Test submission 36",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[12.04424,62.23252]},\"properties\":{\"id\":36,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 36\",\"addedAt\":\"2024-10-01T14:30:55.6523503Z\",\"lastEdited\":\"2024-11-05T02:30:55.6523503Z\",\"radius\":378}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3036",
                            Status = "Akseptert",
                            Timestamp = "2024-10-01T14:30:55.6523500Z"
                        },
                        new
                        {
                            Id = 37L,
                            Comment = "Test submission 37",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[12.15658,62.35009]},\"properties\":{\"id\":37,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 37\",\"addedAt\":\"2024-09-30T14:30:55.6523508Z\",\"lastEdited\":\"2024-11-05T01:30:55.6523509Z\",\"radius\":388.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3037",
                            Status = "Uåpnet",
                            Timestamp = "2024-09-30T14:30:55.6523506Z"
                        },
                        new
                        {
                            Id = 38L,
                            Comment = "Test submission 38",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[12.26892,62.46766]},\"properties\":{\"id\":38,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 38\",\"addedAt\":\"2024-09-29T14:30:55.6523514Z\",\"lastEdited\":\"2024-11-05T00:30:55.6523514Z\",\"radius\":399}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3038",
                            Status = "Under arbeid",
                            Timestamp = "2024-09-29T14:30:55.6523511Z"
                        },
                        new
                        {
                            Id = 39L,
                            Comment = "Test submission 39",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[12.381260000000001,62.58523]},\"properties\":{\"id\":39,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 39\",\"addedAt\":\"2024-09-28T14:30:55.6523519Z\",\"lastEdited\":\"2024-11-04T23:30:55.6523520Z\",\"radius\":409.5}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3039",
                            Status = "Akseptert",
                            Timestamp = "2024-09-28T14:30:55.6523516Z"
                        },
                        new
                        {
                            Id = 40L,
                            Comment = "Test submission 40",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[12.4936,62.702799999999996]},\"properties\":{\"id\":40,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 40\",\"addedAt\":\"2024-09-27T14:30:55.6523524Z\",\"lastEdited\":\"2024-11-04T22:30:55.6523525Z\",\"radius\":420}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3040",
                            Status = "Under arbeid",
                            Timestamp = "2024-09-27T14:30:55.6523521Z"
                        },
                        new
                        {
                            Id = 41L,
                            Comment = "Test submission 41",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[12.60594,62.82037]},\"properties\":{\"id\":41,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 41\",\"addedAt\":\"2024-09-26T14:30:55.6523529Z\",\"lastEdited\":\"2024-11-04T21:30:55.6523530Z\",\"radius\":430.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3041",
                            Status = "Uåpnet",
                            Timestamp = "2024-09-26T14:30:55.6523526Z"
                        },
                        new
                        {
                            Id = 42L,
                            Comment = "Test submission 42",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[12.71828,62.93794]},\"properties\":{\"id\":42,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 42\",\"addedAt\":\"2024-09-25T14:30:55.6523534Z\",\"lastEdited\":\"2024-11-04T20:30:55.6523535Z\",\"radius\":441}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3042",
                            Status = "Akseptert",
                            Timestamp = "2024-09-25T14:30:55.6523532Z"
                        },
                        new
                        {
                            Id = 43L,
                            Comment = "Test submission 43",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[12.83062,63.05551]},\"properties\":{\"id\":43,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 43\",\"addedAt\":\"2024-09-24T14:30:55.6523585Z\",\"lastEdited\":\"2024-11-04T19:30:55.6523586Z\",\"radius\":451.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3043",
                            Status = "Uåpnet",
                            Timestamp = "2024-09-24T14:30:55.6523581Z"
                        },
                        new
                        {
                            Id = 44L,
                            Comment = "Test submission 44",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[12.94296,63.17308]},\"properties\":{\"id\":44,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 44\",\"addedAt\":\"2024-09-23T14:30:55.6523591Z\",\"lastEdited\":\"2024-11-04T18:30:55.6523591Z\",\"radius\":462}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3044",
                            Status = "Under arbeid",
                            Timestamp = "2024-09-23T14:30:55.6523588Z"
                        },
                        new
                        {
                            Id = 45L,
                            Comment = "Test submission 45",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[13.055299999999999,63.29065]},\"properties\":{\"id\":45,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 45\",\"addedAt\":\"2024-09-22T14:30:55.6523596Z\",\"lastEdited\":\"2024-11-04T17:30:55.6523596Z\",\"radius\":472.5}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3045",
                            Status = "Akseptert",
                            Timestamp = "2024-09-22T14:30:55.6523593Z"
                        },
                        new
                        {
                            Id = 46L,
                            Comment = "Test submission 46",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[13.167639999999999,63.40822]},\"properties\":{\"id\":46,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 46\",\"addedAt\":\"2024-09-21T14:30:55.6523601Z\",\"lastEdited\":\"2024-11-04T16:30:55.6523602Z\",\"radius\":483}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3046",
                            Status = "Under arbeid",
                            Timestamp = "2024-09-21T14:30:55.6523598Z"
                        },
                        new
                        {
                            Id = 47L,
                            Comment = "Test submission 47",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[13.27998,63.52579]},\"properties\":{\"id\":47,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 47\",\"addedAt\":\"2024-09-20T14:30:55.6523606Z\",\"lastEdited\":\"2024-11-04T15:30:55.6523607Z\",\"radius\":493.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3047",
                            Status = "Uåpnet",
                            Timestamp = "2024-09-20T14:30:55.6523603Z"
                        },
                        new
                        {
                            Id = 48L,
                            Comment = "Test submission 48",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[13.39232,63.64336]},\"properties\":{\"id\":48,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 48\",\"addedAt\":\"2024-09-19T14:30:55.6523611Z\",\"lastEdited\":\"2024-11-04T14:30:55.6523612Z\",\"radius\":504}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3048",
                            Status = "Akseptert",
                            Timestamp = "2024-09-19T14:30:55.6523609Z"
                        },
                        new
                        {
                            Id = 49L,
                            Comment = "Test submission 49",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[13.50466,63.76093]},\"properties\":{\"id\":49,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 49\",\"addedAt\":\"2024-09-18T14:30:55.6523616Z\",\"lastEdited\":\"2024-11-04T13:30:55.6523617Z\",\"radius\":514.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3049",
                            Status = "Uåpnet",
                            Timestamp = "2024-09-18T14:30:55.6523614Z"
                        },
                        new
                        {
                            Id = 50L,
                            Comment = "Test submission 50",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[13.617,63.8785]},\"properties\":{\"id\":50,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 50\",\"addedAt\":\"2024-09-17T14:30:55.6523622Z\",\"lastEdited\":\"2024-11-04T12:30:55.6523622Z\",\"radius\":525}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3050",
                            Status = "Under arbeid",
                            Timestamp = "2024-09-17T14:30:55.6523619Z"
                        },
                        new
                        {
                            Id = 51L,
                            Comment = "Test submission 51",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[13.72934,63.99607]},\"properties\":{\"id\":51,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 51\",\"addedAt\":\"2024-09-16T14:30:55.6523627Z\",\"lastEdited\":\"2024-11-04T11:30:55.6523628Z\",\"radius\":535.5}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3051",
                            Status = "Akseptert",
                            Timestamp = "2024-09-16T14:30:55.6523624Z"
                        },
                        new
                        {
                            Id = 52L,
                            Comment = "Test submission 52",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[13.84168,64.11364]},\"properties\":{\"id\":52,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 52\",\"addedAt\":\"2024-09-15T14:30:55.6523633Z\",\"lastEdited\":\"2024-11-04T10:30:55.6523633Z\",\"radius\":546}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3052",
                            Status = "Under arbeid",
                            Timestamp = "2024-09-15T14:30:55.6523630Z"
                        },
                        new
                        {
                            Id = 53L,
                            Comment = "Test submission 53",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[13.95402,64.23121]},\"properties\":{\"id\":53,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 53\",\"addedAt\":\"2024-09-14T14:30:55.6523707Z\",\"lastEdited\":\"2024-11-04T09:30:55.6523708Z\",\"radius\":556.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3053",
                            Status = "Uåpnet",
                            Timestamp = "2024-09-14T14:30:55.6523704Z"
                        },
                        new
                        {
                            Id = 54L,
                            Comment = "Test submission 54",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[14.06636,64.34878]},\"properties\":{\"id\":54,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 54\",\"addedAt\":\"2024-09-13T14:30:55.6523712Z\",\"lastEdited\":\"2024-11-04T08:30:55.6523713Z\",\"radius\":567}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3054",
                            Status = "Akseptert",
                            Timestamp = "2024-09-13T14:30:55.6523710Z"
                        },
                        new
                        {
                            Id = 55L,
                            Comment = "Test submission 55",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[14.1787,64.46635]},\"properties\":{\"id\":55,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 55\",\"addedAt\":\"2024-09-12T14:30:55.6523717Z\",\"lastEdited\":\"2024-11-04T07:30:55.6523718Z\",\"radius\":577.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3055",
                            Status = "Uåpnet",
                            Timestamp = "2024-09-12T14:30:55.6523715Z"
                        },
                        new
                        {
                            Id = 56L,
                            Comment = "Test submission 56",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[14.291039999999999,64.58392]},\"properties\":{\"id\":56,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 56\",\"addedAt\":\"2024-09-11T14:30:55.6523722Z\",\"lastEdited\":\"2024-11-04T06:30:55.6523723Z\",\"radius\":588}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3056",
                            Status = "Under arbeid",
                            Timestamp = "2024-09-11T14:30:55.6523720Z"
                        },
                        new
                        {
                            Id = 57L,
                            Comment = "Test submission 57",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[14.403379999999999,64.70149]},\"properties\":{\"id\":57,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 57\",\"addedAt\":\"2024-09-10T14:30:55.6523728Z\",\"lastEdited\":\"2024-11-04T05:30:55.6523728Z\",\"radius\":598.5}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3057",
                            Status = "Akseptert",
                            Timestamp = "2024-09-10T14:30:55.6523725Z"
                        },
                        new
                        {
                            Id = 58L,
                            Comment = "Test submission 58",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[14.51572,64.81906]},\"properties\":{\"id\":58,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 58\",\"addedAt\":\"2024-09-09T14:30:55.6523733Z\",\"lastEdited\":\"2024-11-04T04:30:55.6523734Z\",\"radius\":609}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3058",
                            Status = "Under arbeid",
                            Timestamp = "2024-09-09T14:30:55.6523730Z"
                        },
                        new
                        {
                            Id = 59L,
                            Comment = "Test submission 59",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[14.62806,64.93663]},\"properties\":{\"id\":59,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 59\",\"addedAt\":\"2024-09-08T14:30:55.6523738Z\",\"lastEdited\":\"2024-11-04T03:30:55.6523739Z\",\"radius\":619.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3059",
                            Status = "Uåpnet",
                            Timestamp = "2024-09-08T14:30:55.6523735Z"
                        },
                        new
                        {
                            Id = 60L,
                            Comment = "Test submission 60",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[14.7404,65.0542]},\"properties\":{\"id\":60,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 60\",\"addedAt\":\"2024-09-07T14:30:55.6523743Z\",\"lastEdited\":\"2024-11-04T02:30:55.6523744Z\",\"radius\":630}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3060",
                            Status = "Akseptert",
                            Timestamp = "2024-09-07T14:30:55.6523741Z"
                        },
                        new
                        {
                            Id = 61L,
                            Comment = "Test submission 61",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[14.85274,65.17177]},\"properties\":{\"id\":61,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 61\",\"addedAt\":\"2024-09-06T14:30:55.6523749Z\",\"lastEdited\":\"2024-11-04T01:30:55.6523750Z\",\"radius\":640.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3061",
                            Status = "Uåpnet",
                            Timestamp = "2024-09-06T14:30:55.6523746Z"
                        },
                        new
                        {
                            Id = 62L,
                            Comment = "Test submission 62",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[14.96508,65.28934]},\"properties\":{\"id\":62,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 62\",\"addedAt\":\"2024-09-05T14:30:55.6523754Z\",\"lastEdited\":\"2024-11-04T00:30:55.6523755Z\",\"radius\":651}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3062",
                            Status = "Under arbeid",
                            Timestamp = "2024-09-05T14:30:55.6523751Z"
                        },
                        new
                        {
                            Id = 63L,
                            Comment = "Test submission 63",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[15.07742,65.40691]},\"properties\":{\"id\":63,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 63\",\"addedAt\":\"2024-09-04T14:30:55.6523798Z\",\"lastEdited\":\"2024-11-03T23:30:55.6523799Z\",\"radius\":661.5}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3063",
                            Status = "Akseptert",
                            Timestamp = "2024-09-04T14:30:55.6523795Z"
                        },
                        new
                        {
                            Id = 64L,
                            Comment = "Test submission 64",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[15.18976,65.52448]},\"properties\":{\"id\":64,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 64\",\"addedAt\":\"2024-09-03T14:30:55.6523804Z\",\"lastEdited\":\"2024-11-03T22:30:55.6523805Z\",\"radius\":672}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3064",
                            Status = "Under arbeid",
                            Timestamp = "2024-09-03T14:30:55.6523801Z"
                        },
                        new
                        {
                            Id = 65L,
                            Comment = "Test submission 65",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[15.3021,65.64205]},\"properties\":{\"id\":65,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 65\",\"addedAt\":\"2024-09-02T14:30:55.6523809Z\",\"lastEdited\":\"2024-11-03T21:30:55.6523810Z\",\"radius\":682.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3065",
                            Status = "Uåpnet",
                            Timestamp = "2024-09-02T14:30:55.6523807Z"
                        },
                        new
                        {
                            Id = 66L,
                            Comment = "Test submission 66",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[15.414439999999999,65.75962]},\"properties\":{\"id\":66,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 66\",\"addedAt\":\"2024-09-01T14:30:55.6523816Z\",\"lastEdited\":\"2024-11-03T20:30:55.6523816Z\",\"radius\":693}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3066",
                            Status = "Akseptert",
                            Timestamp = "2024-09-01T14:30:55.6523813Z"
                        },
                        new
                        {
                            Id = 67L,
                            Comment = "Test submission 67",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[15.526779999999999,65.87719]},\"properties\":{\"id\":67,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 67\",\"addedAt\":\"2024-08-31T14:30:55.6523821Z\",\"lastEdited\":\"2024-11-03T19:30:55.6523822Z\",\"radius\":703.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3067",
                            Status = "Uåpnet",
                            Timestamp = "2024-08-31T14:30:55.6523818Z"
                        },
                        new
                        {
                            Id = 68L,
                            Comment = "Test submission 68",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[15.63912,65.99476]},\"properties\":{\"id\":68,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 68\",\"addedAt\":\"2024-08-30T14:30:55.6523826Z\",\"lastEdited\":\"2024-11-03T18:30:55.6523827Z\",\"radius\":714}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3068",
                            Status = "Under arbeid",
                            Timestamp = "2024-08-30T14:30:55.6523824Z"
                        },
                        new
                        {
                            Id = 69L,
                            Comment = "Test submission 69",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[15.75146,66.11233]},\"properties\":{\"id\":69,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 69\",\"addedAt\":\"2024-08-29T14:30:55.6523832Z\",\"lastEdited\":\"2024-11-03T17:30:55.6523832Z\",\"radius\":724.5}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3069",
                            Status = "Akseptert",
                            Timestamp = "2024-08-29T14:30:55.6523829Z"
                        },
                        new
                        {
                            Id = 70L,
                            Comment = "Test submission 70",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[15.8638,66.2299]},\"properties\":{\"id\":70,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 70\",\"addedAt\":\"2024-08-28T14:30:55.6523837Z\",\"lastEdited\":\"2024-11-03T16:30:55.6523837Z\",\"radius\":735}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3070",
                            Status = "Under arbeid",
                            Timestamp = "2024-08-28T14:30:55.6523834Z"
                        },
                        new
                        {
                            Id = 71L,
                            Comment = "Test submission 71",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[15.976140000000001,66.34747]},\"properties\":{\"id\":71,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 71\",\"addedAt\":\"2024-08-27T14:30:55.6523881Z\",\"lastEdited\":\"2024-11-03T15:30:55.6523882Z\",\"radius\":745.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3071",
                            Status = "Uåpnet",
                            Timestamp = "2024-08-27T14:30:55.6523839Z"
                        },
                        new
                        {
                            Id = 72L,
                            Comment = "Test submission 72",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[16.08848,66.46504]},\"properties\":{\"id\":72,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 72\",\"addedAt\":\"2024-08-26T14:30:55.6523887Z\",\"lastEdited\":\"2024-11-03T14:30:55.6523888Z\",\"radius\":756}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3072",
                            Status = "Akseptert",
                            Timestamp = "2024-08-26T14:30:55.6523884Z"
                        },
                        new
                        {
                            Id = 73L,
                            Comment = "Test submission 73",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[16.20082,66.58261]},\"properties\":{\"id\":73,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 73\",\"addedAt\":\"2024-08-25T14:30:55.6523892Z\",\"lastEdited\":\"2024-11-03T13:30:55.6523893Z\",\"radius\":766.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3073",
                            Status = "Uåpnet",
                            Timestamp = "2024-08-25T14:30:55.6523890Z"
                        },
                        new
                        {
                            Id = 74L,
                            Comment = "Test submission 74",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[16.31316,66.70018]},\"properties\":{\"id\":74,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 74\",\"addedAt\":\"2024-08-24T14:30:55.6523898Z\",\"lastEdited\":\"2024-11-03T12:30:55.6523898Z\",\"radius\":777}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3074",
                            Status = "Under arbeid",
                            Timestamp = "2024-08-24T14:30:55.6523895Z"
                        },
                        new
                        {
                            Id = 75L,
                            Comment = "Test submission 75",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[16.4255,66.81775]},\"properties\":{\"id\":75,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 75\",\"addedAt\":\"2024-08-23T14:30:55.6523903Z\",\"lastEdited\":\"2024-11-03T11:30:55.6523904Z\",\"radius\":787.5}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3075",
                            Status = "Akseptert",
                            Timestamp = "2024-08-23T14:30:55.6523900Z"
                        },
                        new
                        {
                            Id = 76L,
                            Comment = "Test submission 76",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[16.53784,66.93532]},\"properties\":{\"id\":76,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 76\",\"addedAt\":\"2024-08-22T14:30:55.6523908Z\",\"lastEdited\":\"2024-11-03T10:30:55.6523909Z\",\"radius\":798}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3076",
                            Status = "Under arbeid",
                            Timestamp = "2024-08-22T14:30:55.6523906Z"
                        },
                        new
                        {
                            Id = 77L,
                            Comment = "Test submission 77",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[16.65018,67.05289]},\"properties\":{\"id\":77,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 77\",\"addedAt\":\"2024-08-21T14:30:55.6523914Z\",\"lastEdited\":\"2024-11-03T09:30:55.6523914Z\",\"radius\":808.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3077",
                            Status = "Uåpnet",
                            Timestamp = "2024-08-21T14:30:55.6523911Z"
                        },
                        new
                        {
                            Id = 78L,
                            Comment = "Test submission 78",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[16.762520000000002,67.17046]},\"properties\":{\"id\":78,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 78\",\"addedAt\":\"2024-08-20T14:30:55.6523919Z\",\"lastEdited\":\"2024-11-03T08:30:55.6523920Z\",\"radius\":819}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3078",
                            Status = "Akseptert",
                            Timestamp = "2024-08-20T14:30:55.6523916Z"
                        },
                        new
                        {
                            Id = 79L,
                            Comment = "Test submission 79",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[16.874859999999998,67.28802999999999]},\"properties\":{\"id\":79,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 79\",\"addedAt\":\"2024-08-19T14:30:55.6523924Z\",\"lastEdited\":\"2024-11-03T07:30:55.6523925Z\",\"radius\":829.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3079",
                            Status = "Uåpnet",
                            Timestamp = "2024-08-19T14:30:55.6523922Z"
                        },
                        new
                        {
                            Id = 80L,
                            Comment = "Test submission 80",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[16.9872,67.40559999999999]},\"properties\":{\"id\":80,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 80\",\"addedAt\":\"2024-08-18T14:30:55.6523930Z\",\"lastEdited\":\"2024-11-03T06:30:55.6523930Z\",\"radius\":840}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3080",
                            Status = "Under arbeid",
                            Timestamp = "2024-08-18T14:30:55.6523927Z"
                        },
                        new
                        {
                            Id = 81L,
                            Comment = "Test submission 81",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[17.099539999999998,67.52317]},\"properties\":{\"id\":81,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 81\",\"addedAt\":\"2024-08-17T14:30:55.6523935Z\",\"lastEdited\":\"2024-11-03T05:30:55.6523963Z\",\"radius\":850.5}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3081",
                            Status = "Akseptert",
                            Timestamp = "2024-08-17T14:30:55.6523932Z"
                        },
                        new
                        {
                            Id = 82L,
                            Comment = "Test submission 82",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[17.21188,67.64074]},\"properties\":{\"id\":82,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 82\",\"addedAt\":\"2024-08-16T14:30:55.6523968Z\",\"lastEdited\":\"2024-11-03T04:30:55.6523968Z\",\"radius\":861}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3082",
                            Status = "Under arbeid",
                            Timestamp = "2024-08-16T14:30:55.6523965Z"
                        },
                        new
                        {
                            Id = 83L,
                            Comment = "Test submission 83",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[17.32422,67.75831]},\"properties\":{\"id\":83,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 83\",\"addedAt\":\"2024-08-15T14:30:55.6523973Z\",\"lastEdited\":\"2024-11-03T03:30:55.6523974Z\",\"radius\":871.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3083",
                            Status = "Uåpnet",
                            Timestamp = "2024-08-15T14:30:55.6523970Z"
                        },
                        new
                        {
                            Id = 84L,
                            Comment = "Test submission 84",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[17.43656,67.87588]},\"properties\":{\"id\":84,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 84\",\"addedAt\":\"2024-08-14T14:30:55.6523978Z\",\"lastEdited\":\"2024-11-03T02:30:55.6523979Z\",\"radius\":882}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3084",
                            Status = "Akseptert",
                            Timestamp = "2024-08-14T14:30:55.6523976Z"
                        },
                        new
                        {
                            Id = 85L,
                            Comment = "Test submission 85",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[17.5489,67.99345]},\"properties\":{\"id\":85,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 85\",\"addedAt\":\"2024-08-13T14:30:55.6523984Z\",\"lastEdited\":\"2024-11-03T01:30:55.6523984Z\",\"radius\":892.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3085",
                            Status = "Uåpnet",
                            Timestamp = "2024-08-13T14:30:55.6523981Z"
                        },
                        new
                        {
                            Id = 86L,
                            Comment = "Test submission 86",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[17.66124,68.11102]},\"properties\":{\"id\":86,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 86\",\"addedAt\":\"2024-08-12T14:30:55.6523989Z\",\"lastEdited\":\"2024-11-03T00:30:55.6523989Z\",\"radius\":903}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3086",
                            Status = "Under arbeid",
                            Timestamp = "2024-08-12T14:30:55.6523986Z"
                        },
                        new
                        {
                            Id = 87L,
                            Comment = "Test submission 87",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[17.77358,68.22859]},\"properties\":{\"id\":87,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 87\",\"addedAt\":\"2024-08-11T14:30:55.6523994Z\",\"lastEdited\":\"2024-11-02T23:30:55.6523995Z\",\"radius\":913.5}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3087",
                            Status = "Akseptert",
                            Timestamp = "2024-08-11T14:30:55.6523991Z"
                        },
                        new
                        {
                            Id = 88L,
                            Comment = "Test submission 88",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[17.88592,68.34616]},\"properties\":{\"id\":88,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 88\",\"addedAt\":\"2024-08-10T14:30:55.6523999Z\",\"lastEdited\":\"2024-11-02T22:30:55.6524000Z\",\"radius\":924}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3088",
                            Status = "Under arbeid",
                            Timestamp = "2024-08-10T14:30:55.6523996Z"
                        },
                        new
                        {
                            Id = 89L,
                            Comment = "Test submission 89",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[17.998260000000002,68.46373]},\"properties\":{\"id\":89,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 89\",\"addedAt\":\"2024-08-09T14:30:55.6524005Z\",\"lastEdited\":\"2024-11-02T21:30:55.6524005Z\",\"radius\":934.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3089",
                            Status = "Uåpnet",
                            Timestamp = "2024-08-09T14:30:55.6524002Z"
                        },
                        new
                        {
                            Id = 90L,
                            Comment = "Test submission 90",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[18.110599999999998,68.5813]},\"properties\":{\"id\":90,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 90\",\"addedAt\":\"2024-08-08T14:30:55.6524010Z\",\"lastEdited\":\"2024-11-02T20:30:55.6524010Z\",\"radius\":945}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3090",
                            Status = "Akseptert",
                            Timestamp = "2024-08-08T14:30:55.6524007Z"
                        },
                        new
                        {
                            Id = 91L,
                            Comment = "Test submission 91",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[18.22294,68.69887]},\"properties\":{\"id\":91,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 91\",\"addedAt\":\"2024-08-07T14:30:55.6524015Z\",\"lastEdited\":\"2024-11-02T19:30:55.6524041Z\",\"radius\":955.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3091",
                            Status = "Uåpnet",
                            Timestamp = "2024-08-07T14:30:55.6524012Z"
                        },
                        new
                        {
                            Id = 92L,
                            Comment = "Test submission 92",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[18.335279999999997,68.81644]},\"properties\":{\"id\":92,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 92\",\"addedAt\":\"2024-08-06T14:30:55.6524046Z\",\"lastEdited\":\"2024-11-02T18:30:55.6524047Z\",\"radius\":966}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3092",
                            Status = "Under arbeid",
                            Timestamp = "2024-08-06T14:30:55.6524043Z"
                        },
                        new
                        {
                            Id = 93L,
                            Comment = "Test submission 93",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[18.44762,68.93401]},\"properties\":{\"id\":93,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 93\",\"addedAt\":\"2024-08-05T14:30:55.6524051Z\",\"lastEdited\":\"2024-11-02T17:30:55.6524052Z\",\"radius\":976.5}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3093",
                            Status = "Akseptert",
                            Timestamp = "2024-08-05T14:30:55.6524049Z"
                        },
                        new
                        {
                            Id = 94L,
                            Comment = "Test submission 94",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[18.55996,69.05158]},\"properties\":{\"id\":94,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 94\",\"addedAt\":\"2024-08-04T14:30:55.6524057Z\",\"lastEdited\":\"2024-11-02T16:30:55.6524057Z\",\"radius\":987}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3094",
                            Status = "Under arbeid",
                            Timestamp = "2024-08-04T14:30:55.6524054Z"
                        },
                        new
                        {
                            Id = 95L,
                            Comment = "Test submission 95",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[18.6723,69.16915]},\"properties\":{\"id\":95,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 95\",\"addedAt\":\"2024-08-03T14:30:55.6524062Z\",\"lastEdited\":\"2024-11-02T15:30:55.6524063Z\",\"radius\":997.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3095",
                            Status = "Uåpnet",
                            Timestamp = "2024-08-03T14:30:55.6524059Z"
                        },
                        new
                        {
                            Id = 96L,
                            Comment = "Test submission 96",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[18.78464,69.28672]},\"properties\":{\"id\":96,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 96\",\"addedAt\":\"2024-08-02T14:30:55.6524067Z\",\"lastEdited\":\"2024-11-02T14:30:55.6524068Z\",\"radius\":1008}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3096",
                            Status = "Akseptert",
                            Timestamp = "2024-08-02T14:30:55.6524065Z"
                        },
                        new
                        {
                            Id = 97L,
                            Comment = "Test submission 97",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[18.89698,69.40429]},\"properties\":{\"id\":97,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 97\",\"addedAt\":\"2024-08-01T14:30:55.6524073Z\",\"lastEdited\":\"2024-11-02T13:30:55.6524073Z\",\"radius\":1018.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3097",
                            Status = "Uåpnet",
                            Timestamp = "2024-08-01T14:30:55.6524070Z"
                        },
                        new
                        {
                            Id = 98L,
                            Comment = "Test submission 98",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[19.00932,69.52186]},\"properties\":{\"id\":98,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 98\",\"addedAt\":\"2024-07-31T14:30:55.6524078Z\",\"lastEdited\":\"2024-11-02T12:30:55.6524078Z\",\"radius\":1029}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3098",
                            Status = "Under arbeid",
                            Timestamp = "2024-07-31T14:30:55.6524075Z"
                        },
                        new
                        {
                            Id = 99L,
                            Comment = "Test submission 99",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[19.12166,69.63943]},\"properties\":{\"id\":99,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 99\",\"addedAt\":\"2024-07-30T14:30:55.6524083Z\",\"lastEdited\":\"2024-11-02T11:30:55.6524084Z\",\"radius\":1039.5}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3099",
                            Status = "Akseptert",
                            Timestamp = "2024-07-30T14:30:55.6524080Z"
                        },
                        new
                        {
                            Id = 100L,
                            Comment = "Test submission 100",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[19.234,69.757]},\"properties\":{\"id\":100,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 100\",\"addedAt\":\"2024-07-29T14:30:55.6524089Z\",\"lastEdited\":\"2024-11-02T10:30:55.6524090Z\",\"radius\":1050}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3100",
                            Status = "Under arbeid",
                            Timestamp = "2024-07-29T14:30:55.6524086Z"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Kartverket_group2.Models.ApplicationUserModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Kartverket_group2.Models.ApplicationUserModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kartverket_group2.Models.ApplicationUserModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Kartverket_group2.Models.ApplicationUserModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
