// <auto-generated />
using System;
using Kartverket_group2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kartverket_group2.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241103144638_AddIdentityTables")]
    partial class AddIdentityTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Kartverket_group2.Models.Submission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "comment");

                    b.Property<string>("GeoJsonData")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "geoJsonData");

                    b.Property<string>("Municipalitynr")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "municipalitynr");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "status");

                    b.Property<string>("Timestamp")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "timestamp");

                    b.HasKey("Id");

                    b.ToTable("Submissions");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Comment = "Test submission 1",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[8.11234,58.11757]},\"properties\":{\"id\":1,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 1\",\"addedAt\":\"2024-11-02T14:46:38.0436125Z\",\"lastEdited\":\"2024-11-03T13:46:38.0436127Z\",\"radius\":10.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3001",
                            Status = "Uåpnet",
                            Timestamp = "2024-11-02T14:46:38.0436085Z"
                        },
                        new
                        {
                            Id = 2L,
                            Comment = "Test submission 2",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[8.22468,58.23514]},\"properties\":{\"id\":2,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 2\",\"addedAt\":\"2024-11-01T14:46:38.0436139Z\",\"lastEdited\":\"2024-11-03T12:46:38.0436139Z\",\"radius\":21}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3002",
                            Status = "Under arbeid",
                            Timestamp = "2024-11-01T14:46:38.0436135Z"
                        },
                        new
                        {
                            Id = 3L,
                            Comment = "Test submission 3",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[8.33702,58.35271]},\"properties\":{\"id\":3,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 3\",\"addedAt\":\"2024-10-31T14:46:38.0436144Z\",\"lastEdited\":\"2024-11-03T11:46:38.0436145Z\",\"radius\":31.5}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3003",
                            Status = "Akseptert",
                            Timestamp = "2024-10-31T14:46:38.0436142Z"
                        },
                        new
                        {
                            Id = 4L,
                            Comment = "Test submission 4",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[8.44936,58.47028]},\"properties\":{\"id\":4,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 4\",\"addedAt\":\"2024-10-30T14:46:38.0436150Z\",\"lastEdited\":\"2024-11-03T10:46:38.0436151Z\",\"radius\":42}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3004",
                            Status = "Under arbeid",
                            Timestamp = "2024-10-30T14:46:38.0436147Z"
                        },
                        new
                        {
                            Id = 5L,
                            Comment = "Test submission 5",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[8.5617,58.58785]},\"properties\":{\"id\":5,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 5\",\"addedAt\":\"2024-10-29T14:46:38.0436155Z\",\"lastEdited\":\"2024-11-03T09:46:38.0436155Z\",\"radius\":52.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3005",
                            Status = "Uåpnet",
                            Timestamp = "2024-10-29T14:46:38.0436152Z"
                        },
                        new
                        {
                            Id = 6L,
                            Comment = "Test submission 6",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[8.67404,58.70542]},\"properties\":{\"id\":6,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 6\",\"addedAt\":\"2024-10-28T14:46:38.0436161Z\",\"lastEdited\":\"2024-11-03T08:46:38.0436162Z\",\"radius\":63}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3006",
                            Status = "Akseptert",
                            Timestamp = "2024-10-28T14:46:38.0436159Z"
                        },
                        new
                        {
                            Id = 7L,
                            Comment = "Test submission 7",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[8.78638,58.82299]},\"properties\":{\"id\":7,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 7\",\"addedAt\":\"2024-10-27T14:46:38.0436167Z\",\"lastEdited\":\"2024-11-03T07:46:38.0436167Z\",\"radius\":73.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3007",
                            Status = "Uåpnet",
                            Timestamp = "2024-10-27T14:46:38.0436164Z"
                        },
                        new
                        {
                            Id = 8L,
                            Comment = "Test submission 8",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[8.89872,58.94056]},\"properties\":{\"id\":8,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 8\",\"addedAt\":\"2024-10-26T14:46:38.0436217Z\",\"lastEdited\":\"2024-11-03T06:46:38.0436218Z\",\"radius\":84}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3008",
                            Status = "Under arbeid",
                            Timestamp = "2024-10-26T14:46:38.0436169Z"
                        },
                        new
                        {
                            Id = 9L,
                            Comment = "Test submission 9",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[9.01106,59.05813]},\"properties\":{\"id\":9,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 9\",\"addedAt\":\"2024-10-25T14:46:38.0436222Z\",\"lastEdited\":\"2024-11-03T05:46:38.0436223Z\",\"radius\":94.5}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3009",
                            Status = "Akseptert",
                            Timestamp = "2024-10-25T14:46:38.0436220Z"
                        },
                        new
                        {
                            Id = 10L,
                            Comment = "Test submission 10",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[9.1234,59.1757]},\"properties\":{\"id\":10,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 10\",\"addedAt\":\"2024-10-24T14:46:38.0436229Z\",\"lastEdited\":\"2024-11-03T04:46:38.0436229Z\",\"radius\":105}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3010",
                            Status = "Under arbeid",
                            Timestamp = "2024-10-24T14:46:38.0436226Z"
                        },
                        new
                        {
                            Id = 11L,
                            Comment = "Test submission 11",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[9.23574,59.29327]},\"properties\":{\"id\":11,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 11\",\"addedAt\":\"2024-10-23T14:46:38.0436234Z\",\"lastEdited\":\"2024-11-03T03:46:38.0436234Z\",\"radius\":115.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3011",
                            Status = "Uåpnet",
                            Timestamp = "2024-10-23T14:46:38.0436231Z"
                        },
                        new
                        {
                            Id = 12L,
                            Comment = "Test submission 12",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[9.34808,59.41084]},\"properties\":{\"id\":12,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 12\",\"addedAt\":\"2024-10-22T14:46:38.0436239Z\",\"lastEdited\":\"2024-11-03T02:46:38.0436239Z\",\"radius\":126}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3012",
                            Status = "Akseptert",
                            Timestamp = "2024-10-22T14:46:38.0436236Z"
                        },
                        new
                        {
                            Id = 13L,
                            Comment = "Test submission 13",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[9.46042,59.52841]},\"properties\":{\"id\":13,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 13\",\"addedAt\":\"2024-10-21T14:46:38.0436244Z\",\"lastEdited\":\"2024-11-03T01:46:38.0436245Z\",\"radius\":136.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3013",
                            Status = "Uåpnet",
                            Timestamp = "2024-10-21T14:46:38.0436241Z"
                        },
                        new
                        {
                            Id = 14L,
                            Comment = "Test submission 14",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[9.57276,59.64598]},\"properties\":{\"id\":14,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 14\",\"addedAt\":\"2024-10-20T14:46:38.0436249Z\",\"lastEdited\":\"2024-11-03T00:46:38.0436250Z\",\"radius\":147}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3014",
                            Status = "Under arbeid",
                            Timestamp = "2024-10-20T14:46:38.0436246Z"
                        },
                        new
                        {
                            Id = 15L,
                            Comment = "Test submission 15",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[9.6851,59.76355]},\"properties\":{\"id\":15,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 15\",\"addedAt\":\"2024-10-19T14:46:38.0436254Z\",\"lastEdited\":\"2024-11-02T23:46:38.0436255Z\",\"radius\":157.5}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3015",
                            Status = "Akseptert",
                            Timestamp = "2024-10-19T14:46:38.0436251Z"
                        },
                        new
                        {
                            Id = 16L,
                            Comment = "Test submission 16",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[9.79744,59.88112]},\"properties\":{\"id\":16,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 16\",\"addedAt\":\"2024-10-18T14:46:38.0436259Z\",\"lastEdited\":\"2024-11-02T22:46:38.0436260Z\",\"radius\":168}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3016",
                            Status = "Under arbeid",
                            Timestamp = "2024-10-18T14:46:38.0436256Z"
                        },
                        new
                        {
                            Id = 17L,
                            Comment = "Test submission 17",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[9.90978,59.998689999999996]},\"properties\":{\"id\":17,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 17\",\"addedAt\":\"2024-10-17T14:46:38.0436264Z\",\"lastEdited\":\"2024-11-02T21:46:38.0436265Z\",\"radius\":178.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3017",
                            Status = "Uåpnet",
                            Timestamp = "2024-10-17T14:46:38.0436262Z"
                        },
                        new
                        {
                            Id = 18L,
                            Comment = "Test submission 18",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[10.022120000000001,60.11626]},\"properties\":{\"id\":18,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 18\",\"addedAt\":\"2024-10-16T14:46:38.0436306Z\",\"lastEdited\":\"2024-11-02T20:46:38.0436307Z\",\"radius\":189}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3018",
                            Status = "Akseptert",
                            Timestamp = "2024-10-16T14:46:38.0436303Z"
                        },
                        new
                        {
                            Id = 19L,
                            Comment = "Test submission 19",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[10.13446,60.23383]},\"properties\":{\"id\":19,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 19\",\"addedAt\":\"2024-10-15T14:46:38.0436311Z\",\"lastEdited\":\"2024-11-02T19:46:38.0436312Z\",\"radius\":199.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3019",
                            Status = "Uåpnet",
                            Timestamp = "2024-10-15T14:46:38.0436309Z"
                        },
                        new
                        {
                            Id = 20L,
                            Comment = "Test submission 20",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[10.2468,60.3514]},\"properties\":{\"id\":20,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 20\",\"addedAt\":\"2024-10-14T14:46:38.0436316Z\",\"lastEdited\":\"2024-11-02T18:46:38.0436317Z\",\"radius\":210}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3020",
                            Status = "Under arbeid",
                            Timestamp = "2024-10-14T14:46:38.0436314Z"
                        },
                        new
                        {
                            Id = 21L,
                            Comment = "Test submission 21",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[10.35914,60.46897]},\"properties\":{\"id\":21,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 21\",\"addedAt\":\"2024-10-13T14:46:38.0436321Z\",\"lastEdited\":\"2024-11-02T17:46:38.0436322Z\",\"radius\":220.5}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3021",
                            Status = "Akseptert",
                            Timestamp = "2024-10-13T14:46:38.0436319Z"
                        },
                        new
                        {
                            Id = 22L,
                            Comment = "Test submission 22",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[10.47148,60.58654]},\"properties\":{\"id\":22,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 22\",\"addedAt\":\"2024-10-12T14:46:38.0436326Z\",\"lastEdited\":\"2024-11-02T16:46:38.0436327Z\",\"radius\":231}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3022",
                            Status = "Under arbeid",
                            Timestamp = "2024-10-12T14:46:38.0436324Z"
                        },
                        new
                        {
                            Id = 23L,
                            Comment = "Test submission 23",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[10.58382,60.70411]},\"properties\":{\"id\":23,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 23\",\"addedAt\":\"2024-10-11T14:46:38.0436331Z\",\"lastEdited\":\"2024-11-02T15:46:38.0436332Z\",\"radius\":241.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3023",
                            Status = "Uåpnet",
                            Timestamp = "2024-10-11T14:46:38.0436329Z"
                        },
                        new
                        {
                            Id = 24L,
                            Comment = "Test submission 24",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[10.696159999999999,60.82168]},\"properties\":{\"id\":24,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 24\",\"addedAt\":\"2024-10-10T14:46:38.0436336Z\",\"lastEdited\":\"2024-11-02T14:46:38.0436337Z\",\"radius\":252}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3024",
                            Status = "Akseptert",
                            Timestamp = "2024-10-10T14:46:38.0436333Z"
                        },
                        new
                        {
                            Id = 25L,
                            Comment = "Test submission 25",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[10.8085,60.93925]},\"properties\":{\"id\":25,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 25\",\"addedAt\":\"2024-10-09T14:46:38.0436341Z\",\"lastEdited\":\"2024-11-02T13:46:38.0436342Z\",\"radius\":262.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3025",
                            Status = "Uåpnet",
                            Timestamp = "2024-10-09T14:46:38.0436338Z"
                        },
                        new
                        {
                            Id = 26L,
                            Comment = "Test submission 26",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[10.92084,61.05682]},\"properties\":{\"id\":26,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 26\",\"addedAt\":\"2024-10-08T14:46:38.0436346Z\",\"lastEdited\":\"2024-11-02T12:46:38.0436347Z\",\"radius\":273}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3026",
                            Status = "Under arbeid",
                            Timestamp = "2024-10-08T14:46:38.0436344Z"
                        },
                        new
                        {
                            Id = 27L,
                            Comment = "Test submission 27",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[11.03318,61.17439]},\"properties\":{\"id\":27,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 27\",\"addedAt\":\"2024-10-07T14:46:38.0436351Z\",\"lastEdited\":\"2024-11-02T11:46:38.0436352Z\",\"radius\":283.5}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3027",
                            Status = "Akseptert",
                            Timestamp = "2024-10-07T14:46:38.0436348Z"
                        },
                        new
                        {
                            Id = 28L,
                            Comment = "Test submission 28",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[11.14552,61.29196]},\"properties\":{\"id\":28,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 28\",\"addedAt\":\"2024-10-06T14:46:38.0436388Z\",\"lastEdited\":\"2024-11-02T10:46:38.0436389Z\",\"radius\":294}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3028",
                            Status = "Under arbeid",
                            Timestamp = "2024-10-06T14:46:38.0436386Z"
                        },
                        new
                        {
                            Id = 29L,
                            Comment = "Test submission 29",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[11.25786,61.40953]},\"properties\":{\"id\":29,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 29\",\"addedAt\":\"2024-10-05T14:46:38.0436394Z\",\"lastEdited\":\"2024-11-02T09:46:38.0436395Z\",\"radius\":304.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3029",
                            Status = "Uåpnet",
                            Timestamp = "2024-10-05T14:46:38.0436391Z"
                        },
                        new
                        {
                            Id = 30L,
                            Comment = "Test submission 30",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[11.3702,61.5271]},\"properties\":{\"id\":30,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 30\",\"addedAt\":\"2024-10-04T14:46:38.0436399Z\",\"lastEdited\":\"2024-11-02T08:46:38.0436400Z\",\"radius\":315}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3030",
                            Status = "Akseptert",
                            Timestamp = "2024-10-04T14:46:38.0436396Z"
                        },
                        new
                        {
                            Id = 31L,
                            Comment = "Test submission 31",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[11.48254,61.64467]},\"properties\":{\"id\":31,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 31\",\"addedAt\":\"2024-10-03T14:46:38.0436404Z\",\"lastEdited\":\"2024-11-02T07:46:38.0436405Z\",\"radius\":325.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3031",
                            Status = "Uåpnet",
                            Timestamp = "2024-10-03T14:46:38.0436401Z"
                        },
                        new
                        {
                            Id = 32L,
                            Comment = "Test submission 32",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[11.59488,61.76224]},\"properties\":{\"id\":32,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 32\",\"addedAt\":\"2024-10-02T14:46:38.0436409Z\",\"lastEdited\":\"2024-11-02T06:46:38.0436410Z\",\"radius\":336}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3032",
                            Status = "Under arbeid",
                            Timestamp = "2024-10-02T14:46:38.0436407Z"
                        },
                        new
                        {
                            Id = 33L,
                            Comment = "Test submission 33",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[11.70722,61.87981]},\"properties\":{\"id\":33,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 33\",\"addedAt\":\"2024-10-01T14:46:38.0436414Z\",\"lastEdited\":\"2024-11-02T05:46:38.0436415Z\",\"radius\":346.5}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3033",
                            Status = "Akseptert",
                            Timestamp = "2024-10-01T14:46:38.0436412Z"
                        },
                        new
                        {
                            Id = 34L,
                            Comment = "Test submission 34",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[11.81956,61.99738]},\"properties\":{\"id\":34,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 34\",\"addedAt\":\"2024-09-30T14:46:38.0436420Z\",\"lastEdited\":\"2024-11-02T04:46:38.0436421Z\",\"radius\":357}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3034",
                            Status = "Under arbeid",
                            Timestamp = "2024-09-30T14:46:38.0436417Z"
                        },
                        new
                        {
                            Id = 35L,
                            Comment = "Test submission 35",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[11.931899999999999,62.11495]},\"properties\":{\"id\":35,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 35\",\"addedAt\":\"2024-09-29T14:46:38.0436425Z\",\"lastEdited\":\"2024-11-02T03:46:38.0436426Z\",\"radius\":367.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3035",
                            Status = "Uåpnet",
                            Timestamp = "2024-09-29T14:46:38.0436422Z"
                        },
                        new
                        {
                            Id = 36L,
                            Comment = "Test submission 36",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[12.04424,62.23252]},\"properties\":{\"id\":36,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 36\",\"addedAt\":\"2024-09-28T14:46:38.0436430Z\",\"lastEdited\":\"2024-11-02T02:46:38.0436431Z\",\"radius\":378}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3036",
                            Status = "Akseptert",
                            Timestamp = "2024-09-28T14:46:38.0436428Z"
                        },
                        new
                        {
                            Id = 37L,
                            Comment = "Test submission 37",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[12.15658,62.35009]},\"properties\":{\"id\":37,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 37\",\"addedAt\":\"2024-09-27T14:46:38.0436467Z\",\"lastEdited\":\"2024-11-02T01:46:38.0436467Z\",\"radius\":388.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3037",
                            Status = "Uåpnet",
                            Timestamp = "2024-09-27T14:46:38.0436433Z"
                        },
                        new
                        {
                            Id = 38L,
                            Comment = "Test submission 38",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[12.26892,62.46766]},\"properties\":{\"id\":38,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 38\",\"addedAt\":\"2024-09-26T14:46:38.0436472Z\",\"lastEdited\":\"2024-11-02T00:46:38.0436473Z\",\"radius\":399}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3038",
                            Status = "Under arbeid",
                            Timestamp = "2024-09-26T14:46:38.0436469Z"
                        },
                        new
                        {
                            Id = 39L,
                            Comment = "Test submission 39",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[12.381260000000001,62.58523]},\"properties\":{\"id\":39,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 39\",\"addedAt\":\"2024-09-25T14:46:38.0436477Z\",\"lastEdited\":\"2024-11-01T23:46:38.0436478Z\",\"radius\":409.5}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3039",
                            Status = "Akseptert",
                            Timestamp = "2024-09-25T14:46:38.0436474Z"
                        },
                        new
                        {
                            Id = 40L,
                            Comment = "Test submission 40",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[12.4936,62.702799999999996]},\"properties\":{\"id\":40,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 40\",\"addedAt\":\"2024-09-24T14:46:38.0436482Z\",\"lastEdited\":\"2024-11-01T22:46:38.0436483Z\",\"radius\":420}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3040",
                            Status = "Under arbeid",
                            Timestamp = "2024-09-24T14:46:38.0436480Z"
                        },
                        new
                        {
                            Id = 41L,
                            Comment = "Test submission 41",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[12.60594,62.82037]},\"properties\":{\"id\":41,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 41\",\"addedAt\":\"2024-09-23T14:46:38.0436487Z\",\"lastEdited\":\"2024-11-01T21:46:38.0436488Z\",\"radius\":430.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3041",
                            Status = "Uåpnet",
                            Timestamp = "2024-09-23T14:46:38.0436485Z"
                        },
                        new
                        {
                            Id = 42L,
                            Comment = "Test submission 42",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[12.71828,62.93794]},\"properties\":{\"id\":42,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 42\",\"addedAt\":\"2024-09-22T14:46:38.0436492Z\",\"lastEdited\":\"2024-11-01T20:46:38.0436493Z\",\"radius\":441}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3042",
                            Status = "Akseptert",
                            Timestamp = "2024-09-22T14:46:38.0436490Z"
                        },
                        new
                        {
                            Id = 43L,
                            Comment = "Test submission 43",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[12.83062,63.05551]},\"properties\":{\"id\":43,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 43\",\"addedAt\":\"2024-09-21T14:46:38.0436497Z\",\"lastEdited\":\"2024-11-01T19:46:38.0436498Z\",\"radius\":451.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3043",
                            Status = "Uåpnet",
                            Timestamp = "2024-09-21T14:46:38.0436495Z"
                        },
                        new
                        {
                            Id = 44L,
                            Comment = "Test submission 44",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[12.94296,63.17308]},\"properties\":{\"id\":44,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 44\",\"addedAt\":\"2024-09-20T14:46:38.0436502Z\",\"lastEdited\":\"2024-11-01T18:46:38.0436503Z\",\"radius\":462}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3044",
                            Status = "Under arbeid",
                            Timestamp = "2024-09-20T14:46:38.0436500Z"
                        },
                        new
                        {
                            Id = 45L,
                            Comment = "Test submission 45",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[13.055299999999999,63.29065]},\"properties\":{\"id\":45,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 45\",\"addedAt\":\"2024-09-19T14:46:38.0436508Z\",\"lastEdited\":\"2024-11-01T17:46:38.0436508Z\",\"radius\":472.5}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3045",
                            Status = "Akseptert",
                            Timestamp = "2024-09-19T14:46:38.0436505Z"
                        },
                        new
                        {
                            Id = 46L,
                            Comment = "Test submission 46",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[13.167639999999999,63.40822]},\"properties\":{\"id\":46,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 46\",\"addedAt\":\"2024-09-18T14:46:38.0436513Z\",\"lastEdited\":\"2024-11-01T16:46:38.0436514Z\",\"radius\":483}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3046",
                            Status = "Under arbeid",
                            Timestamp = "2024-09-18T14:46:38.0436510Z"
                        },
                        new
                        {
                            Id = 47L,
                            Comment = "Test submission 47",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[13.27998,63.52579]},\"properties\":{\"id\":47,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 47\",\"addedAt\":\"2024-09-17T14:46:38.0436535Z\",\"lastEdited\":\"2024-11-01T15:46:38.0436536Z\",\"radius\":493.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3047",
                            Status = "Uåpnet",
                            Timestamp = "2024-09-17T14:46:38.0436515Z"
                        },
                        new
                        {
                            Id = 48L,
                            Comment = "Test submission 48",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[13.39232,63.64336]},\"properties\":{\"id\":48,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 48\",\"addedAt\":\"2024-09-16T14:46:38.0436541Z\",\"lastEdited\":\"2024-11-01T14:46:38.0436542Z\",\"radius\":504}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3048",
                            Status = "Akseptert",
                            Timestamp = "2024-09-16T14:46:38.0436538Z"
                        },
                        new
                        {
                            Id = 49L,
                            Comment = "Test submission 49",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[13.50466,63.76093]},\"properties\":{\"id\":49,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 49\",\"addedAt\":\"2024-09-15T14:46:38.0436546Z\",\"lastEdited\":\"2024-11-01T13:46:38.0436547Z\",\"radius\":514.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3049",
                            Status = "Uåpnet",
                            Timestamp = "2024-09-15T14:46:38.0436544Z"
                        },
                        new
                        {
                            Id = 50L,
                            Comment = "Test submission 50",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[13.617,63.8785]},\"properties\":{\"id\":50,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 50\",\"addedAt\":\"2024-09-14T14:46:38.0436551Z\",\"lastEdited\":\"2024-11-01T12:46:38.0436552Z\",\"radius\":525}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3050",
                            Status = "Under arbeid",
                            Timestamp = "2024-09-14T14:46:38.0436549Z"
                        },
                        new
                        {
                            Id = 51L,
                            Comment = "Test submission 51",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[13.72934,63.99607]},\"properties\":{\"id\":51,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 51\",\"addedAt\":\"2024-09-13T14:46:38.0436556Z\",\"lastEdited\":\"2024-11-01T11:46:38.0436557Z\",\"radius\":535.5}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3051",
                            Status = "Akseptert",
                            Timestamp = "2024-09-13T14:46:38.0436554Z"
                        },
                        new
                        {
                            Id = 52L,
                            Comment = "Test submission 52",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[13.84168,64.11364]},\"properties\":{\"id\":52,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 52\",\"addedAt\":\"2024-09-12T14:46:38.0436562Z\",\"lastEdited\":\"2024-11-01T10:46:38.0436562Z\",\"radius\":546}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3052",
                            Status = "Under arbeid",
                            Timestamp = "2024-09-12T14:46:38.0436559Z"
                        },
                        new
                        {
                            Id = 53L,
                            Comment = "Test submission 53",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[13.95402,64.23121]},\"properties\":{\"id\":53,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 53\",\"addedAt\":\"2024-09-11T14:46:38.0436567Z\",\"lastEdited\":\"2024-11-01T09:46:38.0436567Z\",\"radius\":556.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3053",
                            Status = "Uåpnet",
                            Timestamp = "2024-09-11T14:46:38.0436564Z"
                        },
                        new
                        {
                            Id = 54L,
                            Comment = "Test submission 54",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[14.06636,64.34878]},\"properties\":{\"id\":54,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 54\",\"addedAt\":\"2024-09-10T14:46:38.0436572Z\",\"lastEdited\":\"2024-11-01T08:46:38.0436572Z\",\"radius\":567}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3054",
                            Status = "Akseptert",
                            Timestamp = "2024-09-10T14:46:38.0436569Z"
                        },
                        new
                        {
                            Id = 55L,
                            Comment = "Test submission 55",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[14.1787,64.46635]},\"properties\":{\"id\":55,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 55\",\"addedAt\":\"2024-09-09T14:46:38.0436577Z\",\"lastEdited\":\"2024-11-01T07:46:38.0436577Z\",\"radius\":577.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3055",
                            Status = "Uåpnet",
                            Timestamp = "2024-09-09T14:46:38.0436574Z"
                        },
                        new
                        {
                            Id = 56L,
                            Comment = "Test submission 56",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[14.291039999999999,64.58392]},\"properties\":{\"id\":56,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 56\",\"addedAt\":\"2024-09-08T14:46:38.0436582Z\",\"lastEdited\":\"2024-11-01T06:46:38.0436582Z\",\"radius\":588}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3056",
                            Status = "Under arbeid",
                            Timestamp = "2024-09-08T14:46:38.0436579Z"
                        },
                        new
                        {
                            Id = 57L,
                            Comment = "Test submission 57",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[14.403379999999999,64.70149]},\"properties\":{\"id\":57,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 57\",\"addedAt\":\"2024-09-07T14:46:38.0436640Z\",\"lastEdited\":\"2024-11-01T05:46:38.0436641Z\",\"radius\":598.5}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3057",
                            Status = "Akseptert",
                            Timestamp = "2024-09-07T14:46:38.0436584Z"
                        },
                        new
                        {
                            Id = 58L,
                            Comment = "Test submission 58",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[14.51572,64.81906]},\"properties\":{\"id\":58,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 58\",\"addedAt\":\"2024-09-06T14:46:38.0436646Z\",\"lastEdited\":\"2024-11-01T04:46:38.0436646Z\",\"radius\":609}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3058",
                            Status = "Under arbeid",
                            Timestamp = "2024-09-06T14:46:38.0436643Z"
                        },
                        new
                        {
                            Id = 59L,
                            Comment = "Test submission 59",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[14.62806,64.93663]},\"properties\":{\"id\":59,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 59\",\"addedAt\":\"2024-09-05T14:46:38.0436651Z\",\"lastEdited\":\"2024-11-01T03:46:38.0436652Z\",\"radius\":619.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3059",
                            Status = "Uåpnet",
                            Timestamp = "2024-09-05T14:46:38.0436648Z"
                        },
                        new
                        {
                            Id = 60L,
                            Comment = "Test submission 60",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[14.7404,65.0542]},\"properties\":{\"id\":60,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 60\",\"addedAt\":\"2024-09-04T14:46:38.0436656Z\",\"lastEdited\":\"2024-11-01T02:46:38.0436657Z\",\"radius\":630}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3060",
                            Status = "Akseptert",
                            Timestamp = "2024-09-04T14:46:38.0436653Z"
                        },
                        new
                        {
                            Id = 61L,
                            Comment = "Test submission 61",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[14.85274,65.17177]},\"properties\":{\"id\":61,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 61\",\"addedAt\":\"2024-09-03T14:46:38.0436661Z\",\"lastEdited\":\"2024-11-01T01:46:38.0436662Z\",\"radius\":640.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3061",
                            Status = "Uåpnet",
                            Timestamp = "2024-09-03T14:46:38.0436658Z"
                        },
                        new
                        {
                            Id = 62L,
                            Comment = "Test submission 62",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[14.96508,65.28934]},\"properties\":{\"id\":62,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 62\",\"addedAt\":\"2024-09-02T14:46:38.0436666Z\",\"lastEdited\":\"2024-11-01T00:46:38.0436667Z\",\"radius\":651}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3062",
                            Status = "Under arbeid",
                            Timestamp = "2024-09-02T14:46:38.0436664Z"
                        },
                        new
                        {
                            Id = 63L,
                            Comment = "Test submission 63",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[15.07742,65.40691]},\"properties\":{\"id\":63,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 63\",\"addedAt\":\"2024-09-01T14:46:38.0436671Z\",\"lastEdited\":\"2024-10-31T23:46:38.0436672Z\",\"radius\":661.5}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3063",
                            Status = "Akseptert",
                            Timestamp = "2024-09-01T14:46:38.0436668Z"
                        },
                        new
                        {
                            Id = 64L,
                            Comment = "Test submission 64",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[15.18976,65.52448]},\"properties\":{\"id\":64,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 64\",\"addedAt\":\"2024-08-31T14:46:38.0436676Z\",\"lastEdited\":\"2024-10-31T22:46:38.0436676Z\",\"radius\":672}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3064",
                            Status = "Under arbeid",
                            Timestamp = "2024-08-31T14:46:38.0436673Z"
                        },
                        new
                        {
                            Id = 65L,
                            Comment = "Test submission 65",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[15.3021,65.64205]},\"properties\":{\"id\":65,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 65\",\"addedAt\":\"2024-08-30T14:46:38.0436681Z\",\"lastEdited\":\"2024-10-31T21:46:38.0436681Z\",\"radius\":682.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3065",
                            Status = "Uåpnet",
                            Timestamp = "2024-08-30T14:46:38.0436678Z"
                        },
                        new
                        {
                            Id = 66L,
                            Comment = "Test submission 66",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[15.414439999999999,65.75962]},\"properties\":{\"id\":66,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 66\",\"addedAt\":\"2024-08-29T14:46:38.0436749Z\",\"lastEdited\":\"2024-10-31T20:46:38.0436750Z\",\"radius\":693}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3066",
                            Status = "Akseptert",
                            Timestamp = "2024-08-29T14:46:38.0436700Z"
                        },
                        new
                        {
                            Id = 67L,
                            Comment = "Test submission 67",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[15.526779999999999,65.87719]},\"properties\":{\"id\":67,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 67\",\"addedAt\":\"2024-08-28T14:46:38.0436754Z\",\"lastEdited\":\"2024-10-31T19:46:38.0436755Z\",\"radius\":703.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3067",
                            Status = "Uåpnet",
                            Timestamp = "2024-08-28T14:46:38.0436752Z"
                        },
                        new
                        {
                            Id = 68L,
                            Comment = "Test submission 68",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[15.63912,65.99476]},\"properties\":{\"id\":68,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 68\",\"addedAt\":\"2024-08-27T14:46:38.0436759Z\",\"lastEdited\":\"2024-10-31T18:46:38.0436760Z\",\"radius\":714}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3068",
                            Status = "Under arbeid",
                            Timestamp = "2024-08-27T14:46:38.0436757Z"
                        },
                        new
                        {
                            Id = 69L,
                            Comment = "Test submission 69",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[15.75146,66.11233]},\"properties\":{\"id\":69,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 69\",\"addedAt\":\"2024-08-26T14:46:38.0436764Z\",\"lastEdited\":\"2024-10-31T17:46:38.0436765Z\",\"radius\":724.5}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3069",
                            Status = "Akseptert",
                            Timestamp = "2024-08-26T14:46:38.0436761Z"
                        },
                        new
                        {
                            Id = 70L,
                            Comment = "Test submission 70",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[15.8638,66.2299]},\"properties\":{\"id\":70,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 70\",\"addedAt\":\"2024-08-25T14:46:38.0436769Z\",\"lastEdited\":\"2024-10-31T16:46:38.0436770Z\",\"radius\":735}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3070",
                            Status = "Under arbeid",
                            Timestamp = "2024-08-25T14:46:38.0436766Z"
                        },
                        new
                        {
                            Id = 71L,
                            Comment = "Test submission 71",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[15.976140000000001,66.34747]},\"properties\":{\"id\":71,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 71\",\"addedAt\":\"2024-08-24T14:46:38.0436774Z\",\"lastEdited\":\"2024-10-31T15:46:38.0436774Z\",\"radius\":745.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3071",
                            Status = "Uåpnet",
                            Timestamp = "2024-08-24T14:46:38.0436771Z"
                        },
                        new
                        {
                            Id = 72L,
                            Comment = "Test submission 72",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[16.08848,66.46504]},\"properties\":{\"id\":72,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 72\",\"addedAt\":\"2024-08-23T14:46:38.0436779Z\",\"lastEdited\":\"2024-10-31T14:46:38.0436779Z\",\"radius\":756}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3072",
                            Status = "Akseptert",
                            Timestamp = "2024-08-23T14:46:38.0436776Z"
                        },
                        new
                        {
                            Id = 73L,
                            Comment = "Test submission 73",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[16.20082,66.58261]},\"properties\":{\"id\":73,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 73\",\"addedAt\":\"2024-08-22T14:46:38.0436784Z\",\"lastEdited\":\"2024-10-31T13:46:38.0436784Z\",\"radius\":766.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3073",
                            Status = "Uåpnet",
                            Timestamp = "2024-08-22T14:46:38.0436781Z"
                        },
                        new
                        {
                            Id = 74L,
                            Comment = "Test submission 74",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[16.31316,66.70018]},\"properties\":{\"id\":74,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 74\",\"addedAt\":\"2024-08-21T14:46:38.0436789Z\",\"lastEdited\":\"2024-10-31T12:46:38.0436789Z\",\"radius\":777}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3074",
                            Status = "Under arbeid",
                            Timestamp = "2024-08-21T14:46:38.0436786Z"
                        },
                        new
                        {
                            Id = 75L,
                            Comment = "Test submission 75",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[16.4255,66.81775]},\"properties\":{\"id\":75,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 75\",\"addedAt\":\"2024-08-20T14:46:38.0436794Z\",\"lastEdited\":\"2024-10-31T11:46:38.0436794Z\",\"radius\":787.5}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3075",
                            Status = "Akseptert",
                            Timestamp = "2024-08-20T14:46:38.0436791Z"
                        },
                        new
                        {
                            Id = 76L,
                            Comment = "Test submission 76",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[16.53784,66.93532]},\"properties\":{\"id\":76,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 76\",\"addedAt\":\"2024-08-19T14:46:38.0436830Z\",\"lastEdited\":\"2024-10-31T10:46:38.0436831Z\",\"radius\":798}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3076",
                            Status = "Under arbeid",
                            Timestamp = "2024-08-19T14:46:38.0436796Z"
                        },
                        new
                        {
                            Id = 77L,
                            Comment = "Test submission 77",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[16.65018,67.05289]},\"properties\":{\"id\":77,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 77\",\"addedAt\":\"2024-08-18T14:46:38.0436836Z\",\"lastEdited\":\"2024-10-31T09:46:38.0436836Z\",\"radius\":808.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3077",
                            Status = "Uåpnet",
                            Timestamp = "2024-08-18T14:46:38.0436833Z"
                        },
                        new
                        {
                            Id = 78L,
                            Comment = "Test submission 78",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[16.762520000000002,67.17046]},\"properties\":{\"id\":78,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 78\",\"addedAt\":\"2024-08-17T14:46:38.0436841Z\",\"lastEdited\":\"2024-10-31T08:46:38.0436841Z\",\"radius\":819}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3078",
                            Status = "Akseptert",
                            Timestamp = "2024-08-17T14:46:38.0436838Z"
                        },
                        new
                        {
                            Id = 79L,
                            Comment = "Test submission 79",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[16.874859999999998,67.28802999999999]},\"properties\":{\"id\":79,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 79\",\"addedAt\":\"2024-08-16T14:46:38.0436846Z\",\"lastEdited\":\"2024-10-31T07:46:38.0436846Z\",\"radius\":829.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3079",
                            Status = "Uåpnet",
                            Timestamp = "2024-08-16T14:46:38.0436843Z"
                        },
                        new
                        {
                            Id = 80L,
                            Comment = "Test submission 80",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[16.9872,67.40559999999999]},\"properties\":{\"id\":80,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 80\",\"addedAt\":\"2024-08-15T14:46:38.0436851Z\",\"lastEdited\":\"2024-10-31T06:46:38.0436851Z\",\"radius\":840}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3080",
                            Status = "Under arbeid",
                            Timestamp = "2024-08-15T14:46:38.0436848Z"
                        },
                        new
                        {
                            Id = 81L,
                            Comment = "Test submission 81",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[17.099539999999998,67.52317]},\"properties\":{\"id\":81,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 81\",\"addedAt\":\"2024-08-14T14:46:38.0436856Z\",\"lastEdited\":\"2024-10-31T05:46:38.0436856Z\",\"radius\":850.5}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3081",
                            Status = "Akseptert",
                            Timestamp = "2024-08-14T14:46:38.0436853Z"
                        },
                        new
                        {
                            Id = 82L,
                            Comment = "Test submission 82",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[17.21188,67.64074]},\"properties\":{\"id\":82,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 82\",\"addedAt\":\"2024-08-13T14:46:38.0436861Z\",\"lastEdited\":\"2024-10-31T04:46:38.0436861Z\",\"radius\":861}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3082",
                            Status = "Under arbeid",
                            Timestamp = "2024-08-13T14:46:38.0436858Z"
                        },
                        new
                        {
                            Id = 83L,
                            Comment = "Test submission 83",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[17.32422,67.75831]},\"properties\":{\"id\":83,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 83\",\"addedAt\":\"2024-08-12T14:46:38.0436865Z\",\"lastEdited\":\"2024-10-31T03:46:38.0436866Z\",\"radius\":871.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3083",
                            Status = "Uåpnet",
                            Timestamp = "2024-08-12T14:46:38.0436863Z"
                        },
                        new
                        {
                            Id = 84L,
                            Comment = "Test submission 84",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[17.43656,67.87588]},\"properties\":{\"id\":84,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 84\",\"addedAt\":\"2024-08-11T14:46:38.0436870Z\",\"lastEdited\":\"2024-10-31T02:46:38.0436871Z\",\"radius\":882}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3084",
                            Status = "Akseptert",
                            Timestamp = "2024-08-11T14:46:38.0436868Z"
                        },
                        new
                        {
                            Id = 85L,
                            Comment = "Test submission 85",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[17.5489,67.99345]},\"properties\":{\"id\":85,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 85\",\"addedAt\":\"2024-08-10T14:46:38.0436876Z\",\"lastEdited\":\"2024-10-31T01:46:38.0436876Z\",\"radius\":892.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3085",
                            Status = "Uåpnet",
                            Timestamp = "2024-08-10T14:46:38.0436873Z"
                        },
                        new
                        {
                            Id = 86L,
                            Comment = "Test submission 86",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[17.66124,68.11102]},\"properties\":{\"id\":86,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 86\",\"addedAt\":\"2024-08-09T14:46:38.0436912Z\",\"lastEdited\":\"2024-10-31T00:46:38.0436913Z\",\"radius\":903}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3086",
                            Status = "Under arbeid",
                            Timestamp = "2024-08-09T14:46:38.0436878Z"
                        },
                        new
                        {
                            Id = 87L,
                            Comment = "Test submission 87",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[17.77358,68.22859]},\"properties\":{\"id\":87,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 87\",\"addedAt\":\"2024-08-08T14:46:38.0436918Z\",\"lastEdited\":\"2024-10-30T23:46:38.0436918Z\",\"radius\":913.5}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3087",
                            Status = "Akseptert",
                            Timestamp = "2024-08-08T14:46:38.0436915Z"
                        },
                        new
                        {
                            Id = 88L,
                            Comment = "Test submission 88",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[17.88592,68.34616]},\"properties\":{\"id\":88,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 88\",\"addedAt\":\"2024-08-07T14:46:38.0436923Z\",\"lastEdited\":\"2024-10-30T22:46:38.0436924Z\",\"radius\":924}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3088",
                            Status = "Under arbeid",
                            Timestamp = "2024-08-07T14:46:38.0436920Z"
                        },
                        new
                        {
                            Id = 89L,
                            Comment = "Test submission 89",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[17.998260000000002,68.46373]},\"properties\":{\"id\":89,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 89\",\"addedAt\":\"2024-08-06T14:46:38.0436928Z\",\"lastEdited\":\"2024-10-30T21:46:38.0436928Z\",\"radius\":934.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3089",
                            Status = "Uåpnet",
                            Timestamp = "2024-08-06T14:46:38.0436925Z"
                        },
                        new
                        {
                            Id = 90L,
                            Comment = "Test submission 90",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[18.110599999999998,68.5813]},\"properties\":{\"id\":90,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 90\",\"addedAt\":\"2024-08-05T14:46:38.0436933Z\",\"lastEdited\":\"2024-10-30T20:46:38.0436933Z\",\"radius\":945}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3090",
                            Status = "Akseptert",
                            Timestamp = "2024-08-05T14:46:38.0436930Z"
                        },
                        new
                        {
                            Id = 91L,
                            Comment = "Test submission 91",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[18.22294,68.69887]},\"properties\":{\"id\":91,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 91\",\"addedAt\":\"2024-08-04T14:46:38.0436938Z\",\"lastEdited\":\"2024-10-30T19:46:38.0436938Z\",\"radius\":955.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3091",
                            Status = "Uåpnet",
                            Timestamp = "2024-08-04T14:46:38.0436935Z"
                        },
                        new
                        {
                            Id = 92L,
                            Comment = "Test submission 92",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[18.335279999999997,68.81644]},\"properties\":{\"id\":92,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 92\",\"addedAt\":\"2024-08-03T14:46:38.0436943Z\",\"lastEdited\":\"2024-10-30T18:46:38.0436943Z\",\"radius\":966}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3092",
                            Status = "Under arbeid",
                            Timestamp = "2024-08-03T14:46:38.0436940Z"
                        },
                        new
                        {
                            Id = 93L,
                            Comment = "Test submission 93",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[18.44762,68.93401]},\"properties\":{\"id\":93,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 93\",\"addedAt\":\"2024-08-02T14:46:38.0436948Z\",\"lastEdited\":\"2024-10-30T17:46:38.0436948Z\",\"radius\":976.5}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3093",
                            Status = "Akseptert",
                            Timestamp = "2024-08-02T14:46:38.0436945Z"
                        },
                        new
                        {
                            Id = 94L,
                            Comment = "Test submission 94",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[18.55996,69.05158]},\"properties\":{\"id\":94,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 94\",\"addedAt\":\"2024-08-01T14:46:38.0436953Z\",\"lastEdited\":\"2024-10-30T16:46:38.0436953Z\",\"radius\":987}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3094",
                            Status = "Under arbeid",
                            Timestamp = "2024-08-01T14:46:38.0436950Z"
                        },
                        new
                        {
                            Id = 95L,
                            Comment = "Test submission 95",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[18.6723,69.16915]},\"properties\":{\"id\":95,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 95\",\"addedAt\":\"2024-07-31T14:46:38.0436958Z\",\"lastEdited\":\"2024-10-30T15:46:38.0436958Z\",\"radius\":997.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3095",
                            Status = "Uåpnet",
                            Timestamp = "2024-07-31T14:46:38.0436955Z"
                        },
                        new
                        {
                            Id = 96L,
                            Comment = "Test submission 96",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[18.78464,69.28672]},\"properties\":{\"id\":96,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 96\",\"addedAt\":\"2024-07-30T14:46:38.0436963Z\",\"lastEdited\":\"2024-10-30T14:46:38.0436995Z\",\"radius\":1008}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3096",
                            Status = "Akseptert",
                            Timestamp = "2024-07-30T14:46:38.0436960Z"
                        },
                        new
                        {
                            Id = 97L,
                            Comment = "Test submission 97",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[18.89698,69.40429]},\"properties\":{\"id\":97,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 97\",\"addedAt\":\"2024-07-29T14:46:38.0437001Z\",\"lastEdited\":\"2024-10-30T13:46:38.0437001Z\",\"radius\":1018.5}}],\"activeTileLayer\":\"Sattelitt\"}",
                            Municipalitynr = "3097",
                            Status = "Uåpnet",
                            Timestamp = "2024-07-29T14:46:38.0436998Z"
                        },
                        new
                        {
                            Id = 98L,
                            Comment = "Test submission 98",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[19.00932,69.52186]},\"properties\":{\"id\":98,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 98\",\"addedAt\":\"2024-07-28T14:46:38.0437006Z\",\"lastEdited\":\"2024-10-30T12:46:38.0437006Z\",\"radius\":1029}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3098",
                            Status = "Under arbeid",
                            Timestamp = "2024-07-28T14:46:38.0437003Z"
                        },
                        new
                        {
                            Id = 99L,
                            Comment = "Test submission 99",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[19.12166,69.63943]},\"properties\":{\"id\":99,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 99\",\"addedAt\":\"2024-07-27T14:46:38.0437011Z\",\"lastEdited\":\"2024-10-30T11:46:38.0437011Z\",\"radius\":1039.5}}],\"activeTileLayer\":\"Standard\"}",
                            Municipalitynr = "3099",
                            Status = "Akseptert",
                            Timestamp = "2024-07-27T14:46:38.0437008Z"
                        },
                        new
                        {
                            Id = 100L,
                            Comment = "Test submission 100",
                            GeoJsonData = "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[19.234,69.757]},\"properties\":{\"id\":100,\"type\":\"Mark\\u00F8r\",\"comment\":\"Feature comment 100\",\"addedAt\":\"2024-07-26T14:46:38.0437016Z\",\"lastEdited\":\"2024-10-30T10:46:38.0437017Z\",\"radius\":1050}}],\"activeTileLayer\":\"Turkart\"}",
                            Municipalitynr = "3100",
                            Status = "Under arbeid",
                            Timestamp = "2024-07-26T14:46:38.0437013Z"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
